# Setup

Import library dan dataset dipakai bersama oleh Task 1 dan Task 2.

In [1]:
# download my recently edited files from GitHub if running this notebook in Google Colab
!mkdir -p src
!wget -N -P src https://raw.githubusercontent.com/teranixbq/SequenceModellingNLP/refs/heads/main/src/char_level.py
!wget -N -P src https://raw.githubusercontent.com/teranixbq/SequenceModellingNLP/refs/heads/main/src/word_level.py

--2026-05-15 12:06:10--  https://raw.githubusercontent.com/teranixbq/SequenceModellingNLP/refs/heads/main/src/char_level.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3882 (3.8K) [text/plain]
Saving to: ‘src/char_level.py’

char_level.py       100%[===================>]   3.79K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2026-05-15 12:06:10 (82.4 MB/s) - ‘src/char_level.py’ saved [3882/3882]

--2026-05-15 12:06:10--  https://raw.githubusercontent.com/teranixbq/SequenceModellingNLP/refs/heads/main/src/word_level.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3835 (3.7K) [text/plain]
Saving to: ‘src/word_level.py’

word_level.py       100%[===================>]   3.75K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2026-05-15 12:06:11 (83.9 MB/s) - ‘src/word_level.py’ saved [3835/3835]

In [2]:
import re
from collections import Counter
from pathlib import Path

import kagglehub
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Subset, TensorDataset, random_split

from src.word_level import TextCNN, HierarchicalTextCNN
from src.char_level import CharCNN, HierarchicalCharCNN

## Download dan Baca Dataset

In [3]:
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")
print("Path to dataset files:", path)

csv_path = next(Path(path).glob("*.csv"))
df = pd.read_csv(csv_path)

reviews = df["review"].tolist()
labels = (df["sentiment"] == "positive").astype(int).tolist()


print("Jumlah data:", len(reviews))
print("Contoh label:", labels[0])

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-50k-movie-reviews
Jumlah data: 50000
Contoh label: 1

# Task 1 - Word-level 1D CNN

## Tokenisasi, Vocabulary, dan Encoding

Review harus diubah menjadi angka: tokenisasi memecah kalimat jadi kata, vocabulary memberi ID untuk setiap kata, encoding mengubah review menjadi deretan ID dengan panjang yang sama.

In [4]:
def tokenize(text):
    return re.findall(r"[A-Za-z0-9']+", text.lower())

def encode_review(text, word_to_id, max_length):
    token_ids = [word_to_id.get(token, word_to_id["<unk>"]) for token in tokenize(text)]
    token_ids = token_ids[:max_length]
    token_ids += [word_to_id["<pad>"]] * (max_length - len(token_ids))
    return token_ids

In [5]:
max_vocab_size = 50000
max_length = 200
batch_size = 32
num_epochs = 3

word_counter = Counter()
for review in reviews:
    word_counter.update(tokenize(review))

word_to_id = {"<pad>": 0, "<unk>": 1}

for word, _ in word_counter.most_common(max_vocab_size - 2):
    word_to_id[word] = len(word_to_id)

vocab_size = len(word_to_id)
print("Vocab size:", vocab_size)

Vocab size: 50000

## Buat DataLoader

In [6]:
encoded_reviews = [encode_review(review, word_to_id, max_length) for review in reviews]

batch_x = torch.tensor(encoded_reviews, dtype=torch.long)
batch_y = torch.tensor(labels, dtype=torch.long)

dataset = TensorDataset(batch_x, batch_y)
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(
    dataset,
    [train_size, val_size],
    generator=torch.Generator().manual_seed(42)
)

train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size)

print("Shape X:", batch_x.shape)
print("Shape y:", batch_y.shape)
print("Train data:", len(train_dataset))
print("Validation data:", len(val_dataset))

Shape X: torch.Size([50000, 200])
Shape y: torch.Size([50000])
Train data: 40000
Validation data: 10000

## Compare Pooling Performance

Bagian akhir ini langsung membandingkan `max`, `avg`, `none` atau without pooling, dan optional `adaptive`.

In [7]:
from time import perf_counter
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

if "trained_models" not in globals():
    trained_models = {}


def train_and_evaluate(pooling_type, kernel_sizes = [3, 4]):
    model = TextCNN(
        vocab_size=vocab_size,
        embed_dim=300,
        num_filters=100,
        kernel_sizes=kernel_sizes,
        num_classes=2,
        pooling_type=pooling_type,
        sequence_length=max_length,
    ).to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    print(f"Start training pooling: {pooling_type}, Kernel sizes: {kernel_sizes}", flush=True)

    if device == "cuda":
        torch.cuda.synchronize()

    start_time = perf_counter()

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0

        for batch_idx, (batch_x, batch_y) in enumerate(train_dataloader, start=1):
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

            if batch_idx % 50 == 0 or batch_idx == len(train_dataloader):
                print(
                    f"Pooling: {pooling_type}, Epoch {epoch + 1}/{num_epochs}, "
                    f"Batch {batch_idx}/{len(train_dataloader)}, "
                    f"Loss: {total_loss / batch_idx:.4f}",
                    flush=True,
                )

    if device == "cuda":
        torch.cuda.synchronize()

    training_time = perf_counter() - start_time

    model.eval()
    y_true = []
    y_pred = []

    with torch.no_grad():
        for batch_x, batch_y in val_dataloader:
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            outputs = model(batch_x)
            probabilities = torch.softmax(outputs, dim=1)
            predictions = probabilities.argmax(dim=1)

            y_true += batch_y.cpu().tolist()
            y_pred += predictions.cpu().tolist()

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    model_key = f"word_cnn_{pooling_type}_{'_'.join(map(str, kernel_sizes))}"
    trained_models[model_key] = model

    return {
        "model_type": "word_cnn",
        "pooling_type": pooling_type,
        "kernel_sizes": kernel_sizes,
        "model_key": model_key,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1_score": f1,
        "training_time": training_time,
    }

Using device: cuda

In [8]:
results = []

for pooling_type in ["max", "avg", "none", "adaptive"]:
    record = train_and_evaluate(pooling_type)
    results.append(record)

    print(
        f"Model: {record['model_type']}, "
        f"Pooling: {record['pooling_type']}, "
        f"Kernel Sizes: {record['kernel_sizes']}, "
        f"Accuracy: {record['accuracy']:.4f}, "
        f"Precision: {record['precision']:.4f}, "
        f"Recall: {record['recall']:.4f}, "
        f"F1: {record['f1_score']:.4f}, "
        f"Training Time: {record['training_time']:.2f}s",
        flush=True,
    )

Start training pooling: max, Kernel sizes: [3, 4]
Pooling: max, Epoch 1/3, Batch 50/1250, Loss: 0.8444
Pooling: max, Epoch 1/3, Batch 100/1250, Loss: 0.8130
Pooling: max, Epoch 1/3, Batch 150/1250, Loss: 0.7641
Pooling: max, Epoch 1/3, Batch 200/1250, Loss: 0.7283
Pooling: max, Epoch 1/3, Batch 250/1250, Loss: 0.7068
Pooling: max, Epoch 1/3, Batch 300/1250, Loss: 0.6858
Pooling: max, Epoch 1/3, Batch 350/1250, Loss: 0.6696
Pooling: max, Epoch 1/3, Batch 400/1250, Loss: 0.6584
Pooling: max, Epoch 1/3, Batch 450/1250, Loss: 0.6494
Pooling: max, Epoch 1/3, Batch 500/1250, Loss: 0.6388
Pooling: max, Epoch 1/3, Batch 550/1250, Loss: 0.6299
Pooling: max, Epoch 1/3, Batch 600/1250, Loss: 0.6213
Pooling: max, Epoch 1/3, Batch 650/1250, Loss: 0.6137
Pooling: max, Epoch 1/3, Batch 700/1250, Loss: 0.6073
Pooling: max, Epoch 1/3, Batch 750/1250, Loss: 0.6013
Pooling: max, Epoch 1/3, Batch 800/1250, Loss: 0.5960
Pooling: max, Epoch 1/3, Batch 850/1250, Loss: 0.5916
Pooling: max, Epoch 1/3, Batch 900/1250, Loss: 0.5865
Pooling: max, Epoch 1/3, Batch 950/1250, Loss: 0.5822
Pooling: max, Epoch 1/3, Batch 1000/1250, Loss: 0.5784
Pooling: max, Epoch 1/3, Batch 1050/1250, Loss: 0.5735
Pooling: max, Epoch 1/3, Batch 1100/1250, Loss: 0.5709
Pooling: max, Epoch 1/3, Batch 1150/1250, Loss: 0.5676
Pooling: max, Epoch 1/3, Batch 1200/1250, Loss: 0.5648
Pooling: max, Epoch 1/3, Batch 1250/1250, Loss: 0.5614
Pooling: max, Epoch 2/3, Batch 50/1250, Loss: 0.4380
Pooling: max, Epoch 2/3, Batch 100/1250, Loss: 0.4380
Pooling: max, Epoch 2/3, Batch 150/1250, Loss: 0.4370
Pooling: max, Epoch 2/3, Batch 200/1250, Loss: 0.4393
Pooling: max, Epoch 2/3, Batch 250/1250, Loss: 0.4383
Pooling: max, Epoch 2/3, Batch 300/1250, Loss: 0.4325
Pooling: max, Epoch 2/3, Batch 350/1250, Loss: 0.4364
Pooling: max, Epoch 2/3, Batch 400/1250, Loss: 0.4390
Pooling: max, Epoch 2/3, Batch 450/1250, Loss: 0.4366
Pooling: max, Epoch 2/3, Batch 500/1250, Loss: 0.4351
Pooling: max, Epoch 2/3, Batch 550/1250, Loss: 0.4361
Pooling: max, Epoch 2/3, Batch 600/1250, Loss: 0.4344
Pooling: max, Epoch 2/3, Batch 650/1250, Loss: 0.4320
Pooling: max, Epoch 2/3, Batch 700/1250, Loss: 0.4284
Pooling: max, Epoch 2/3, Batch 750/1250, Loss: 0.4275
Pooling: max, Epoch 2/3, Batch 800/1250, Loss: 0.4276
Pooling: max, Epoch 2/3, Batch 850/1250, Loss: 0.4252
Pooling: max, Epoch 2/3, Batch 900/1250, Loss: 0.4259
Pooling: max, Epoch 2/3, Batch 950/1250, Loss: 0.4240
Pooling: max, Epoch 2/3, Batch 1000/1250, Loss: 0.4236
Pooling: max, Epoch 2/3, Batch 1050/1250, Loss: 0.4221
Pooling: max, Epoch 2/3, Batch 1100/1250, Loss: 0.4211
Pooling: max, Epoch 2/3, Batch 1150/1250, Loss: 0.4205
Pooling: max, Epoch 2/3, Batch 1200/1250, Loss: 0.4194
Pooling: max, Epoch 2/3, Batch 1250/1250, Loss: 0.4184
Pooling: max, Epoch 3/3, Batch 50/1250, Loss: 0.3422
Pooling: max, Epoch 3/3, Batch 100/1250, Loss: 0.3358
Pooling: max, Epoch 3/3, Batch 150/1250, Loss: 0.3271
Pooling: max, Epoch 3/3, Batch 200/1250, Loss: 0.3286
Pooling: max, Epoch 3/3, Batch 250/1250, Loss: 0.3279
Pooling: max, Epoch 3/3, Batch 300/1250, Loss: 0.3245
Pooling: max, Epoch 3/3, Batch 350/1250, Loss: 0.3244
Pooling: max, Epoch 3/3, Batch 400/1250, Loss: 0.3243
Pooling: max, Epoch 3/3, Batch 450/1250, Loss: 0.3248
Pooling: max, Epoch 3/3, Batch 500/1250, Loss: 0.3257
Pooling: max, Epoch 3/3, Batch 550/1250, Loss: 0.3252
Pooling: max, Epoch 3/3, Batch 600/1250, Loss: 0.3270
Pooling: max, Epoch 3/3, Batch 650/1250, Loss: 0.3278
Pooling: max, Epoch 3/3, Batch 700/1250, Loss: 0.3274
Pooling: max, Epoch 3/3, Batch 750/1250, Loss: 0.3261
Pooling: max, Epoch 3/3, Batch 800/1250, Loss: 0.3245
Pooling: max, Epoch 3/3, Batch 850/1250, Loss: 0.3234
Pooling: max, Epoch 3/3, Batch 900/1250, Loss: 0.3238
Pooling: max, Epoch 3/3, Batch 950/1250, Loss: 0.3229
Pooling: max, Epoch 3/3, Batch 1000/1250, Loss: 0.3219
Pooling: max, Epoch 3/3, Batch 1050/1250, Loss: 0.3217
Pooling: max, Epoch 3/3, Batch 1100/1250, Loss: 0.3210
Pooling: max, Epoch 3/3, Batch 1150/1250, Loss: 0.3213
Pooling: max, Epoch 3/3, Batch 1200/1250, Loss: 0.3218
Pooling: max, Epoch 3/3, Batch 1250/1250, Loss: 0.3222
Model: word_cnn, Pooling: max, Kernel Sizes: [3, 4], Accuracy: 0.8658, Precision: 0.8928, Recall: 0.8336, F1: 0.8622, Training Time: 39.27s
Start training pooling: avg, Kernel sizes: [3, 4]
Pooling: avg, Epoch 1/3, Batch 50/1250, Loss: 0.6795
Pooling: avg, Epoch 1/3, Batch 100/1250, Loss: 0.6561
Pooling: avg, Epoch 1/3, Batch 150/1250, Loss: 0.6344
Pooling: avg, Epoch 1/3, Batch 200/1250, Loss: 0.6111
Pooling: avg, Epoch 1/3, Batch 250/1250, Loss: 0.5888
Pooling: avg, Epoch 1/3, Batch 300/1250, Loss: 0.5677
Pooling: avg, Epoch 1/3, Batch 350/1250, Loss: 0.5492
Pooling: avg, Epoch 1/3, Batch 400/1250, Loss: 0.5327
Pooling: avg, Epoch 1/3, Batch 450/1250, Loss: 0.5171
Pooling: avg, Epoch 1/3, Batch 500/1250, Loss: 0.5039
Pooling: avg, Epoch 1/3, Batch 550/1250, Loss: 0.4936
Pooling: avg, Epoch 1/3, Batch 600/1250, Loss: 0.4832
Pooling: avg, Epoch 1/3, Batch 650/1250, Loss: 0.4735
Pooling: avg, Epoch 1/3, Batch 700/1250, Loss: 0.4652
Pooling: avg, Epoch 1/3, Batch 750/1250, Loss: 0.4578
Pooling: avg, Epoch 1/3, Batch 800/1250, Loss: 0.4503
Pooling: avg, Epoch 1/3, Batch 850/1250, Loss: 0.4444
Pooling: avg, Epoch 1/3, Batch 900/1250, Loss: 0.4396
Pooling: avg, Epoch 1/3, Batch 950/1250, Loss: 0.4346
Pooling: avg, Epoch 1/3, Batch 1000/1250, Loss: 0.4286
Pooling: avg, Epoch 1/3, Batch 1050/1250, Loss: 0.4245
Pooling: avg, Epoch 1/3, Batch 1100/1250, Loss: 0.4188
Pooling: avg, Epoch 1/3, Batch 1150/1250, Loss: 0.4142
Pooling: avg, Epoch 1/3, Batch 1200/1250, Loss: 0.4108
Pooling: avg, Epoch 1/3, Batch 1250/1250, Loss: 0.4069
Pooling: avg, Epoch 2/3, Batch 50/1250, Loss: 0.2392
Pooling: avg, Epoch 2/3, Batch 100/1250, Loss: 0.2439
Pooling: avg, Epoch 2/3, Batch 150/1250, Loss: 0.2482
Pooling: avg, Epoch 2/3, Batch 200/1250, Loss: 0.2449
Pooling: avg, Epoch 2/3, Batch 250/1250, Loss: 0.2419
Pooling: avg, Epoch 2/3, Batch 300/1250, Loss: 0.2437
Pooling: avg, Epoch 2/3, Batch 350/1250, Loss: 0.2470
Pooling: avg, Epoch 2/3, Batch 400/1250, Loss: 0.2471
Pooling: avg, Epoch 2/3, Batch 450/1250, Loss: 0.2460
Pooling: avg, Epoch 2/3, Batch 500/1250, Loss: 0.2462
Pooling: avg, Epoch 2/3, Batch 550/1250, Loss: 0.2468
Pooling: avg, Epoch 2/3, Batch 600/1250, Loss: 0.2475
Pooling: avg, Epoch 2/3, Batch 650/1250, Loss: 0.2488
Pooling: avg, Epoch 2/3, Batch 700/1250, Loss: 0.2479
Pooling: avg, Epoch 2/3, Batch 750/1250, Loss: 0.2471
Pooling: avg, Epoch 2/3, Batch 800/1250, Loss: 0.2480
Pooling: avg, Epoch 2/3, Batch 850/1250, Loss: 0.2470
Pooling: avg, Epoch 2/3, Batch 900/1250, Loss: 0.2459
Pooling: avg, Epoch 2/3, Batch 950/1250, Loss: 0.2458
Pooling: avg, Epoch 2/3, Batch 1000/1250, Loss: 0.2458
Pooling: avg, Epoch 2/3, Batch 1050/1250, Loss: 0.2468
Pooling: avg, Epoch 2/3, Batch 1100/1250, Loss: 0.2449
Pooling: avg, Epoch 2/3, Batch 1150/1250, Loss: 0.2439
Pooling: avg, Epoch 2/3, Batch 1200/1250, Loss: 0.2449
Pooling: avg, Epoch 2/3, Batch 1250/1250, Loss: 0.2447
Pooling: avg, Epoch 3/3, Batch 50/1250, Loss: 0.1541
Pooling: avg, Epoch 3/3, Batch 100/1250, Loss: 0.1649
Pooling: avg, Epoch 3/3, Batch 150/1250, Loss: 0.1702
Pooling: avg, Epoch 3/3, Batch 200/1250, Loss: 0.1674
Pooling: avg, Epoch 3/3, Batch 250/1250, Loss: 0.1668
Pooling: avg, Epoch 3/3, Batch 300/1250, Loss: 0.1671
Pooling: avg, Epoch 3/3, Batch 350/1250, Loss: 0.1645
Pooling: avg, Epoch 3/3, Batch 400/1250, Loss: 0.1657
Pooling: avg, Epoch 3/3, Batch 450/1250, Loss: 0.1658
Pooling: avg, Epoch 3/3, Batch 500/1250, Loss: 0.1676
Pooling: avg, Epoch 3/3, Batch 550/1250, Loss: 0.1690
Pooling: avg, Epoch 3/3, Batch 600/1250, Loss: 0.1689
Pooling: avg, Epoch 3/3, Batch 650/1250, Loss: 0.1708
Pooling: avg, Epoch 3/3, Batch 700/1250, Loss: 0.1720
Pooling: avg, Epoch 3/3, Batch 750/1250, Loss: 0.1716
Pooling: avg, Epoch 3/3, Batch 800/1250, Loss: 0.1713
Pooling: avg, Epoch 3/3, Batch 850/1250, Loss: 0.1718
Pooling: avg, Epoch 3/3, Batch 900/1250, Loss: 0.1718
Pooling: avg, Epoch 3/3, Batch 950/1250, Loss: 0.1732
Pooling: avg, Epoch 3/3, Batch 1000/1250, Loss: 0.1721
Pooling: avg, Epoch 3/3, Batch 1050/1250, Loss: 0.1720
Pooling: avg, Epoch 3/3, Batch 1100/1250, Loss: 0.1719
Pooling: avg, Epoch 3/3, Batch 1150/1250, Loss: 0.1727
Pooling: avg, Epoch 3/3, Batch 1200/1250, Loss: 0.1731
Pooling: avg, Epoch 3/3, Batch 1250/1250, Loss: 0.1732
Model: word_cnn, Pooling: avg, Kernel Sizes: [3, 4], Accuracy: 0.8782, Precision: 0.8701, Recall: 0.8912, F1: 0.8805, Training Time: 40.78s
Start training pooling: none, Kernel sizes: [3, 4]
Pooling: none, Epoch 1/3, Batch 50/1250, Loss: 0.9057
Pooling: none, Epoch 1/3, Batch 100/1250, Loss: 0.9115
Pooling: none, Epoch 1/3, Batch 150/1250, Loss: 0.9083
Pooling: none, Epoch 1/3, Batch 200/1250, Loss: 0.9221
Pooling: none, Epoch 1/3, Batch 250/1250, Loss: 0.9331
Pooling: none, Epoch 1/3, Batch 300/1250, Loss: 0.9562
Pooling: none, Epoch 1/3, Batch 350/1250, Loss: 0.9566
Pooling: none, Epoch 1/3, Batch 400/1250, Loss: 0.9916
Pooling: none, Epoch 1/3, Batch 450/1250, Loss: 0.9985
Pooling: none, Epoch 1/3, Batch 500/1250, Loss: 0.9967
Pooling: none, Epoch 1/3, Batch 550/1250, Loss: 0.9908
Pooling: none, Epoch 1/3, Batch 600/1250, Loss: 0.9886
Pooling: none, Epoch 1/3, Batch 650/1250, Loss: 0.9934
Pooling: none, Epoch 1/3, Batch 700/1250, Loss: 0.9958
Pooling: none, Epoch 1/3, Batch 750/1250, Loss: 0.9920
Pooling: none, Epoch 1/3, Batch 800/1250, Loss: 0.9889
Pooling: none, Epoch 1/3, Batch 850/1250, Loss: 0.9795
Pooling: none, Epoch 1/3, Batch 900/1250, Loss: 0.9752
Pooling: none, Epoch 1/3, Batch 950/1250, Loss: 0.9666
Pooling: none, Epoch 1/3, Batch 1000/1250, Loss: 0.9585
Pooling: none, Epoch 1/3, Batch 1050/1250, Loss: 0.9548
Pooling: none, Epoch 1/3, Batch 1100/1250, Loss: 0.9499
Pooling: none, Epoch 1/3, Batch 1150/1250, Loss: 0.9407
Pooling: none, Epoch 1/3, Batch 1200/1250, Loss: 0.9358
Pooling: none, Epoch 1/3, Batch 1250/1250, Loss: 0.9317
Pooling: none, Epoch 2/3, Batch 50/1250, Loss: 0.3999
Pooling: none, Epoch 2/3, Batch 100/1250, Loss: 0.4103
Pooling: none, Epoch 2/3, Batch 150/1250, Loss: 0.4068
Pooling: none, Epoch 2/3, Batch 200/1250, Loss: 0.4223
Pooling: none, Epoch 2/3, Batch 250/1250, Loss: 0.4098
Pooling: none, Epoch 2/3, Batch 300/1250, Loss: 0.4156
Pooling: none, Epoch 2/3, Batch 350/1250, Loss: 0.4247
Pooling: none, Epoch 2/3, Batch 400/1250, Loss: 0.4287
Pooling: none, Epoch 2/3, Batch 450/1250, Loss: 0.4242
Pooling: none, Epoch 2/3, Batch 500/1250, Loss: 0.4286
Pooling: none, Epoch 2/3, Batch 550/1250, Loss: 0.4340
Pooling: none, Epoch 2/3, Batch 600/1250, Loss: 0.4332
Pooling: none, Epoch 2/3, Batch 650/1250, Loss: 0.4360
Pooling: none, Epoch 2/3, Batch 700/1250, Loss: 0.4371
Pooling: none, Epoch 2/3, Batch 750/1250, Loss: 0.4424
Pooling: none, Epoch 2/3, Batch 800/1250, Loss: 0.4458
Pooling: none, Epoch 2/3, Batch 850/1250, Loss: 0.4482
Pooling: none, Epoch 2/3, Batch 900/1250, Loss: 0.4548
Pooling: none, Epoch 2/3, Batch 950/1250, Loss: 0.4555
Pooling: none, Epoch 2/3, Batch 1000/1250, Loss: 0.4586
Pooling: none, Epoch 2/3, Batch 1050/1250, Loss: 0.4619
Pooling: none, Epoch 2/3, Batch 1100/1250, Loss: 0.4659
Pooling: none, Epoch 2/3, Batch 1150/1250, Loss: 0.4672
Pooling: none, Epoch 2/3, Batch 1200/1250, Loss: 0.4716
Pooling: none, Epoch 2/3, Batch 1250/1250, Loss: 0.4763
Pooling: none, Epoch 3/3, Batch 50/1250, Loss: 0.2861
Pooling: none, Epoch 3/3, Batch 100/1250, Loss: 0.2746
Pooling: none, Epoch 3/3, Batch 150/1250, Loss: 0.2707
Pooling: none, Epoch 3/3, Batch 200/1250, Loss: 0.2782
Pooling: none, Epoch 3/3, Batch 250/1250, Loss: 0.2788
Pooling: none, Epoch 3/3, Batch 300/1250, Loss: 0.2874
Pooling: none, Epoch 3/3, Batch 350/1250, Loss: 0.2876
Pooling: none, Epoch 3/3, Batch 400/1250, Loss: 0.2963
Pooling: none, Epoch 3/3, Batch 450/1250, Loss: 0.3057
Pooling: none, Epoch 3/3, Batch 500/1250, Loss: 0.3094
Pooling: none, Epoch 3/3, Batch 550/1250, Loss: 0.3155
Pooling: none, Epoch 3/3, Batch 600/1250, Loss: 0.3192
Pooling: none, Epoch 3/3, Batch 650/1250, Loss: 0.3219
Pooling: none, Epoch 3/3, Batch 700/1250, Loss: 0.3256
Pooling: none, Epoch 3/3, Batch 750/1250, Loss: 0.3271
Pooling: none, Epoch 3/3, Batch 800/1250, Loss: 0.3317
Pooling: none, Epoch 3/3, Batch 850/1250, Loss: 0.3361
Pooling: none, Epoch 3/3, Batch 900/1250, Loss: 0.3381
Pooling: none, Epoch 3/3, Batch 950/1250, Loss: 0.3392
Pooling: none, Epoch 3/3, Batch 1000/1250, Loss: 0.3456
Pooling: none, Epoch 3/3, Batch 1050/1250, Loss: 0.3496
Pooling: none, Epoch 3/3, Batch 1100/1250, Loss: 0.3540
Pooling: none, Epoch 3/3, Batch 1150/1250, Loss: 0.3589
Pooling: none, Epoch 3/3, Batch 1200/1250, Loss: 0.3651
Pooling: none, Epoch 3/3, Batch 1250/1250, Loss: 0.3709
Model: word_cnn, Pooling: none, Kernel Sizes: [3, 4], Accuracy: 0.8227, Precision: 0.8656, Recall: 0.7671, F1: 0.8134, Training Time: 40.17s
Start training pooling: adaptive, Kernel sizes: [3, 4]
Pooling: adaptive, Epoch 1/3, Batch 50/1250, Loss: 0.8540
Pooling: adaptive, Epoch 1/3, Batch 100/1250, Loss: 0.8179
Pooling: adaptive, Epoch 1/3, Batch 150/1250, Loss: 0.7777
Pooling: adaptive, Epoch 1/3, Batch 200/1250, Loss: 0.7532
Pooling: adaptive, Epoch 1/3, Batch 250/1250, Loss: 0.7355
Pooling: adaptive, Epoch 1/3, Batch 300/1250, Loss: 0.7163
Pooling: adaptive, Epoch 1/3, Batch 350/1250, Loss: 0.7034
Pooling: adaptive, Epoch 1/3, Batch 400/1250, Loss: 0.6880
Pooling: adaptive, Epoch 1/3, Batch 450/1250, Loss: 0.6742
Pooling: adaptive, Epoch 1/3, Batch 500/1250, Loss: 0.6641
Pooling: adaptive, Epoch 1/3, Batch 550/1250, Loss: 0.6593
Pooling: adaptive, Epoch 1/3, Batch 600/1250, Loss: 0.6517
Pooling: adaptive, Epoch 1/3, Batch 650/1250, Loss: 0.6430
Pooling: adaptive, Epoch 1/3, Batch 700/1250, Loss: 0.6371
Pooling: adaptive, Epoch 1/3, Batch 750/1250, Loss: 0.6277
Pooling: adaptive, Epoch 1/3, Batch 800/1250, Loss: 0.6185
Pooling: adaptive, Epoch 1/3, Batch 850/1250, Loss: 0.6096
Pooling: adaptive, Epoch 1/3, Batch 900/1250, Loss: 0.6011
Pooling: adaptive, Epoch 1/3, Batch 950/1250, Loss: 0.5938
Pooling: adaptive, Epoch 1/3, Batch 1000/1250, Loss: 0.5880
Pooling: adaptive, Epoch 1/3, Batch 1050/1250, Loss: 0.5811
Pooling: adaptive, Epoch 1/3, Batch 1100/1250, Loss: 0.5777
Pooling: adaptive, Epoch 1/3, Batch 1150/1250, Loss: 0.5729
Pooling: adaptive, Epoch 1/3, Batch 1200/1250, Loss: 0.5692
Pooling: adaptive, Epoch 1/3, Batch 1250/1250, Loss: 0.5640
Pooling: adaptive, Epoch 2/3, Batch 50/1250, Loss: 0.3638
Pooling: adaptive, Epoch 2/3, Batch 100/1250, Loss: 0.3831
Pooling: adaptive, Epoch 2/3, Batch 150/1250, Loss: 0.3895
Pooling: adaptive, Epoch 2/3, Batch 200/1250, Loss: 0.3917
Pooling: adaptive, Epoch 2/3, Batch 250/1250, Loss: 0.3985
Pooling: adaptive, Epoch 2/3, Batch 300/1250, Loss: 0.3961
Pooling: adaptive, Epoch 2/3, Batch 350/1250, Loss: 0.3922
Pooling: adaptive, Epoch 2/3, Batch 400/1250, Loss: 0.3874
Pooling: adaptive, Epoch 2/3, Batch 450/1250, Loss: 0.3901
Pooling: adaptive, Epoch 2/3, Batch 500/1250, Loss: 0.3852
Pooling: adaptive, Epoch 2/3, Batch 550/1250, Loss: 0.3852
Pooling: adaptive, Epoch 2/3, Batch 600/1250, Loss: 0.3835
Pooling: adaptive, Epoch 2/3, Batch 650/1250, Loss: 0.3805
Pooling: adaptive, Epoch 2/3, Batch 700/1250, Loss: 0.3787
Pooling: adaptive, Epoch 2/3, Batch 750/1250, Loss: 0.3805
Pooling: adaptive, Epoch 2/3, Batch 800/1250, Loss: 0.3820
Pooling: adaptive, Epoch 2/3, Batch 850/1250, Loss: 0.3793
Pooling: adaptive, Epoch 2/3, Batch 900/1250, Loss: 0.3815
Pooling: adaptive, Epoch 2/3, Batch 950/1250, Loss: 0.3791
Pooling: adaptive, Epoch 2/3, Batch 1000/1250, Loss: 0.3780
Pooling: adaptive, Epoch 2/3, Batch 1050/1250, Loss: 0.3785
Pooling: adaptive, Epoch 2/3, Batch 1100/1250, Loss: 0.3775
Pooling: adaptive, Epoch 2/3, Batch 1150/1250, Loss: 0.3778
Pooling: adaptive, Epoch 2/3, Batch 1200/1250, Loss: 0.3761
Pooling: adaptive, Epoch 2/3, Batch 1250/1250, Loss: 0.3751
Pooling: adaptive, Epoch 3/3, Batch 50/1250, Loss: 0.2251
Pooling: adaptive, Epoch 3/3, Batch 100/1250, Loss: 0.2332
Pooling: adaptive, Epoch 3/3, Batch 150/1250, Loss: 0.2439
Pooling: adaptive, Epoch 3/3, Batch 200/1250, Loss: 0.2436
Pooling: adaptive, Epoch 3/3, Batch 250/1250, Loss: 0.2477
Pooling: adaptive, Epoch 3/3, Batch 300/1250, Loss: 0.2490
Pooling: adaptive, Epoch 3/3, Batch 350/1250, Loss: 0.2495
Pooling: adaptive, Epoch 3/3, Batch 400/1250, Loss: 0.2482
Pooling: adaptive, Epoch 3/3, Batch 450/1250, Loss: 0.2498
Pooling: adaptive, Epoch 3/3, Batch 500/1250, Loss: 0.2515
Pooling: adaptive, Epoch 3/3, Batch 550/1250, Loss: 0.2537
Pooling: adaptive, Epoch 3/3, Batch 600/1250, Loss: 0.2541
Pooling: adaptive, Epoch 3/3, Batch 650/1250, Loss: 0.2562
Pooling: adaptive, Epoch 3/3, Batch 700/1250, Loss: 0.2567
Pooling: adaptive, Epoch 3/3, Batch 750/1250, Loss: 0.2579
Pooling: adaptive, Epoch 3/3, Batch 800/1250, Loss: 0.2588
Pooling: adaptive, Epoch 3/3, Batch 850/1250, Loss: 0.2600
Pooling: adaptive, Epoch 3/3, Batch 900/1250, Loss: 0.2597
Pooling: adaptive, Epoch 3/3, Batch 950/1250, Loss: 0.2604
Pooling: adaptive, Epoch 3/3, Batch 1000/1250, Loss: 0.2617
Pooling: adaptive, Epoch 3/3, Batch 1050/1250, Loss: 0.2628
Pooling: adaptive, Epoch 3/3, Batch 1100/1250, Loss: 0.2651
Pooling: adaptive, Epoch 3/3, Batch 1150/1250, Loss: 0.2681
Pooling: adaptive, Epoch 3/3, Batch 1200/1250, Loss: 0.2712
Pooling: adaptive, Epoch 3/3, Batch 1250/1250, Loss: 0.2707
Model: word_cnn, Pooling: adaptive, Kernel Sizes: [3, 4], Accuracy: 0.8578, Precision: 0.8183, Recall: 0.9226, F1: 0.8673, Training Time: 39.62s

### Compare World - CNN with 4 kernel sizes

Meenggunaakn kernel size lain untuk membandingkan dengan compare sebelumnya apakah ada perbedaan atau tidak

In [9]:
for pooling_type in ["max", "avg", "none", "adaptive"]:
    record = train_and_evaluate(pooling_type, kernel_sizes=[3, 4, 5, 6])
    results.append(record)

    print(
        f"Model: {record['model_type']}, "
        f"Pooling: {record['pooling_type']}, "
        f"Kernel Sizes: {record['kernel_sizes']}, "
        f"Accuracy: {record['accuracy']:.4f}, "
        f"Precision: {record['precision']:.4f}, "
        f"Recall: {record['recall']:.4f}, "
        f"F1: {record['f1_score']:.4f}, "
        f"Training Time: {record['training_time']:.2f}s",
        flush=True,
    )

Start training pooling: max, Kernel sizes: [3, 4, 5, 6]
Pooling: max, Epoch 1/3, Batch 50/1250, Loss: 0.9262
Pooling: max, Epoch 1/3, Batch 100/1250, Loss: 0.8483
Pooling: max, Epoch 1/3, Batch 150/1250, Loss: 0.8033
Pooling: max, Epoch 1/3, Batch 200/1250, Loss: 0.7749
Pooling: max, Epoch 1/3, Batch 250/1250, Loss: 0.7446
Pooling: max, Epoch 1/3, Batch 300/1250, Loss: 0.7298
Pooling: max, Epoch 1/3, Batch 350/1250, Loss: 0.7123
Pooling: max, Epoch 1/3, Batch 400/1250, Loss: 0.6997
Pooling: max, Epoch 1/3, Batch 450/1250, Loss: 0.6833
Pooling: max, Epoch 1/3, Batch 500/1250, Loss: 0.6712
Pooling: max, Epoch 1/3, Batch 550/1250, Loss: 0.6625
Pooling: max, Epoch 1/3, Batch 600/1250, Loss: 0.6523
Pooling: max, Epoch 1/3, Batch 650/1250, Loss: 0.6440
Pooling: max, Epoch 1/3, Batch 700/1250, Loss: 0.6404
Pooling: max, Epoch 1/3, Batch 750/1250, Loss: 0.6339
Pooling: max, Epoch 1/3, Batch 800/1250, Loss: 0.6261
Pooling: max, Epoch 1/3, Batch 850/1250, Loss: 0.6208
Pooling: max, Epoch 1/3, Batch 900/1250, Loss: 0.6141
Pooling: max, Epoch 1/3, Batch 950/1250, Loss: 0.6097
Pooling: max, Epoch 1/3, Batch 1000/1250, Loss: 0.6049
Pooling: max, Epoch 1/3, Batch 1050/1250, Loss: 0.5997
Pooling: max, Epoch 1/3, Batch 1100/1250, Loss: 0.5967
Pooling: max, Epoch 1/3, Batch 1150/1250, Loss: 0.5926
Pooling: max, Epoch 1/3, Batch 1200/1250, Loss: 0.5879
Pooling: max, Epoch 1/3, Batch 1250/1250, Loss: 0.5857
Pooling: max, Epoch 2/3, Batch 50/1250, Loss: 0.4622
Pooling: max, Epoch 2/3, Batch 100/1250, Loss: 0.4537
Pooling: max, Epoch 2/3, Batch 150/1250, Loss: 0.4494
Pooling: max, Epoch 2/3, Batch 200/1250, Loss: 0.4382
Pooling: max, Epoch 2/3, Batch 250/1250, Loss: 0.4344
Pooling: max, Epoch 2/3, Batch 300/1250, Loss: 0.4335
Pooling: max, Epoch 2/3, Batch 350/1250, Loss: 0.4307
Pooling: max, Epoch 2/3, Batch 400/1250, Loss: 0.4267
Pooling: max, Epoch 2/3, Batch 450/1250, Loss: 0.4292
Pooling: max, Epoch 2/3, Batch 500/1250, Loss: 0.4325
Pooling: max, Epoch 2/3, Batch 550/1250, Loss: 0.4337
Pooling: max, Epoch 2/3, Batch 600/1250, Loss: 0.4301
Pooling: max, Epoch 2/3, Batch 650/1250, Loss: 0.4298
Pooling: max, Epoch 2/3, Batch 700/1250, Loss: 0.4274
Pooling: max, Epoch 2/3, Batch 750/1250, Loss: 0.4261
Pooling: max, Epoch 2/3, Batch 800/1250, Loss: 0.4246
Pooling: max, Epoch 2/3, Batch 850/1250, Loss: 0.4216
Pooling: max, Epoch 2/3, Batch 900/1250, Loss: 0.4211
Pooling: max, Epoch 2/3, Batch 950/1250, Loss: 0.4207
Pooling: max, Epoch 2/3, Batch 1000/1250, Loss: 0.4188
Pooling: max, Epoch 2/3, Batch 1050/1250, Loss: 0.4171
Pooling: max, Epoch 2/3, Batch 1100/1250, Loss: 0.4147
Pooling: max, Epoch 2/3, Batch 1150/1250, Loss: 0.4136
Pooling: max, Epoch 2/3, Batch 1200/1250, Loss: 0.4122
Pooling: max, Epoch 2/3, Batch 1250/1250, Loss: 0.4109
Pooling: max, Epoch 3/3, Batch 50/1250, Loss: 0.2987
Pooling: max, Epoch 3/3, Batch 100/1250, Loss: 0.3068
Pooling: max, Epoch 3/3, Batch 150/1250, Loss: 0.2938
Pooling: max, Epoch 3/3, Batch 200/1250, Loss: 0.2916
Pooling: max, Epoch 3/3, Batch 250/1250, Loss: 0.2874
Pooling: max, Epoch 3/3, Batch 300/1250, Loss: 0.2923
Pooling: max, Epoch 3/3, Batch 350/1250, Loss: 0.2931
Pooling: max, Epoch 3/3, Batch 400/1250, Loss: 0.2958
Pooling: max, Epoch 3/3, Batch 450/1250, Loss: 0.2937
Pooling: max, Epoch 3/3, Batch 500/1250, Loss: 0.2904
Pooling: max, Epoch 3/3, Batch 550/1250, Loss: 0.2907
Pooling: max, Epoch 3/3, Batch 600/1250, Loss: 0.2927
Pooling: max, Epoch 3/3, Batch 650/1250, Loss: 0.2896
Pooling: max, Epoch 3/3, Batch 700/1250, Loss: 0.2918
Pooling: max, Epoch 3/3, Batch 750/1250, Loss: 0.2936
Pooling: max, Epoch 3/3, Batch 800/1250, Loss: 0.2944
Pooling: max, Epoch 3/3, Batch 850/1250, Loss: 0.2976
Pooling: max, Epoch 3/3, Batch 900/1250, Loss: 0.2974
Pooling: max, Epoch 3/3, Batch 950/1250, Loss: 0.2971
Pooling: max, Epoch 3/3, Batch 1000/1250, Loss: 0.2993
Pooling: max, Epoch 3/3, Batch 1050/1250, Loss: 0.2998
Pooling: max, Epoch 3/3, Batch 1100/1250, Loss: 0.3011
Pooling: max, Epoch 3/3, Batch 1150/1250, Loss: 0.3018
Pooling: max, Epoch 3/3, Batch 1200/1250, Loss: 0.3023
Pooling: max, Epoch 3/3, Batch 1250/1250, Loss: 0.3015
Model: word_cnn, Pooling: max, Kernel Sizes: [3, 4, 5, 6], Accuracy: 0.8621, Precision: 0.8375, Recall: 0.9011, F1: 0.8681, Training Time: 65.11s
Start training pooling: avg, Kernel sizes: [3, 4, 5, 6]
Pooling: avg, Epoch 1/3, Batch 50/1250, Loss: 0.6681
Pooling: avg, Epoch 1/3, Batch 100/1250, Loss: 0.6420
Pooling: avg, Epoch 1/3, Batch 150/1250, Loss: 0.6215
Pooling: avg, Epoch 1/3, Batch 200/1250, Loss: 0.6018
Pooling: avg, Epoch 1/3, Batch 250/1250, Loss: 0.5733
Pooling: avg, Epoch 1/3, Batch 300/1250, Loss: 0.5527
Pooling: avg, Epoch 1/3, Batch 350/1250, Loss: 0.5345
Pooling: avg, Epoch 1/3, Batch 400/1250, Loss: 0.5202
Pooling: avg, Epoch 1/3, Batch 450/1250, Loss: 0.5056
Pooling: avg, Epoch 1/3, Batch 500/1250, Loss: 0.4949
Pooling: avg, Epoch 1/3, Batch 550/1250, Loss: 0.4852
Pooling: avg, Epoch 1/3, Batch 600/1250, Loss: 0.4774
Pooling: avg, Epoch 1/3, Batch 650/1250, Loss: 0.4680
Pooling: avg, Epoch 1/3, Batch 700/1250, Loss: 0.4598
Pooling: avg, Epoch 1/3, Batch 750/1250, Loss: 0.4522
Pooling: avg, Epoch 1/3, Batch 800/1250, Loss: 0.4445
Pooling: avg, Epoch 1/3, Batch 850/1250, Loss: 0.4395
Pooling: avg, Epoch 1/3, Batch 900/1250, Loss: 0.4346
Pooling: avg, Epoch 1/3, Batch 950/1250, Loss: 0.4297
Pooling: avg, Epoch 1/3, Batch 1000/1250, Loss: 0.4243
Pooling: avg, Epoch 1/3, Batch 1050/1250, Loss: 0.4182
Pooling: avg, Epoch 1/3, Batch 1100/1250, Loss: 0.4144
Pooling: avg, Epoch 1/3, Batch 1150/1250, Loss: 0.4110
Pooling: avg, Epoch 1/3, Batch 1200/1250, Loss: 0.4076
Pooling: avg, Epoch 1/3, Batch 1250/1250, Loss: 0.4039
Pooling: avg, Epoch 2/3, Batch 50/1250, Loss: 0.2362
Pooling: avg, Epoch 2/3, Batch 100/1250, Loss: 0.2373
Pooling: avg, Epoch 2/3, Batch 150/1250, Loss: 0.2433
Pooling: avg, Epoch 2/3, Batch 200/1250, Loss: 0.2458
Pooling: avg, Epoch 2/3, Batch 250/1250, Loss: 0.2441
Pooling: avg, Epoch 2/3, Batch 300/1250, Loss: 0.2403
Pooling: avg, Epoch 2/3, Batch 350/1250, Loss: 0.2419
Pooling: avg, Epoch 2/3, Batch 400/1250, Loss: 0.2421
Pooling: avg, Epoch 2/3, Batch 450/1250, Loss: 0.2399
Pooling: avg, Epoch 2/3, Batch 500/1250, Loss: 0.2393
Pooling: avg, Epoch 2/3, Batch 550/1250, Loss: 0.2380
Pooling: avg, Epoch 2/3, Batch 600/1250, Loss: 0.2378
Pooling: avg, Epoch 2/3, Batch 650/1250, Loss: 0.2367
Pooling: avg, Epoch 2/3, Batch 700/1250, Loss: 0.2360
Pooling: avg, Epoch 2/3, Batch 750/1250, Loss: 0.2364
Pooling: avg, Epoch 2/3, Batch 800/1250, Loss: 0.2359
Pooling: avg, Epoch 2/3, Batch 850/1250, Loss: 0.2355
Pooling: avg, Epoch 2/3, Batch 900/1250, Loss: 0.2361
Pooling: avg, Epoch 2/3, Batch 950/1250, Loss: 0.2364
Pooling: avg, Epoch 2/3, Batch 1000/1250, Loss: 0.2354
Pooling: avg, Epoch 2/3, Batch 1050/1250, Loss: 0.2362
Pooling: avg, Epoch 2/3, Batch 1100/1250, Loss: 0.2364
Pooling: avg, Epoch 2/3, Batch 1150/1250, Loss: 0.2359
Pooling: avg, Epoch 2/3, Batch 1200/1250, Loss: 0.2353
Pooling: avg, Epoch 2/3, Batch 1250/1250, Loss: 0.2356
Pooling: avg, Epoch 3/3, Batch 50/1250, Loss: 0.1490
Pooling: avg, Epoch 3/3, Batch 100/1250, Loss: 0.1489
Pooling: avg, Epoch 3/3, Batch 150/1250, Loss: 0.1492
Pooling: avg, Epoch 3/3, Batch 200/1250, Loss: 0.1501
Pooling: avg, Epoch 3/3, Batch 250/1250, Loss: 0.1512
Pooling: avg, Epoch 3/3, Batch 300/1250, Loss: 0.1516
Pooling: avg, Epoch 3/3, Batch 350/1250, Loss: 0.1534
Pooling: avg, Epoch 3/3, Batch 400/1250, Loss: 0.1544
Pooling: avg, Epoch 3/3, Batch 450/1250, Loss: 0.1550
Pooling: avg, Epoch 3/3, Batch 500/1250, Loss: 0.1567
Pooling: avg, Epoch 3/3, Batch 550/1250, Loss: 0.1578
Pooling: avg, Epoch 3/3, Batch 600/1250, Loss: 0.1601
Pooling: avg, Epoch 3/3, Batch 650/1250, Loss: 0.1590
Pooling: avg, Epoch 3/3, Batch 700/1250, Loss: 0.1605
Pooling: avg, Epoch 3/3, Batch 750/1250, Loss: 0.1609
Pooling: avg, Epoch 3/3, Batch 800/1250, Loss: 0.1608
Pooling: avg, Epoch 3/3, Batch 850/1250, Loss: 0.1617
Pooling: avg, Epoch 3/3, Batch 900/1250, Loss: 0.1629
Pooling: avg, Epoch 3/3, Batch 950/1250, Loss: 0.1625
Pooling: avg, Epoch 3/3, Batch 1000/1250, Loss: 0.1637
Pooling: avg, Epoch 3/3, Batch 1050/1250, Loss: 0.1640
Pooling: avg, Epoch 3/3, Batch 1100/1250, Loss: 0.1641
Pooling: avg, Epoch 3/3, Batch 1150/1250, Loss: 0.1645
Pooling: avg, Epoch 3/3, Batch 1200/1250, Loss: 0.1648
Pooling: avg, Epoch 3/3, Batch 1250/1250, Loss: 0.1644
Model: word_cnn, Pooling: avg, Kernel Sizes: [3, 4, 5, 6], Accuracy: 0.8790, Precision: 0.8647, Recall: 0.9007, F1: 0.8823, Training Time: 67.19s
Start training pooling: none, Kernel sizes: [3, 4, 5, 6]
Pooling: none, Epoch 1/3, Batch 50/1250, Loss: 1.6145
Pooling: none, Epoch 1/3, Batch 100/1250, Loss: 1.2476
Pooling: none, Epoch 1/3, Batch 150/1250, Loss: 1.1683
Pooling: none, Epoch 1/3, Batch 200/1250, Loss: 1.1696
Pooling: none, Epoch 1/3, Batch 250/1250, Loss: 1.1977
Pooling: none, Epoch 1/3, Batch 300/1250, Loss: 1.2414
Pooling: none, Epoch 1/3, Batch 350/1250, Loss: 1.2578
Pooling: none, Epoch 1/3, Batch 400/1250, Loss: 1.2674
Pooling: none, Epoch 1/3, Batch 450/1250, Loss: 1.2794
Pooling: none, Epoch 1/3, Batch 500/1250, Loss: 1.2787
Pooling: none, Epoch 1/3, Batch 550/1250, Loss: 1.2802
Pooling: none, Epoch 1/3, Batch 600/1250, Loss: 1.2898
Pooling: none, Epoch 1/3, Batch 650/1250, Loss: 1.2917
Pooling: none, Epoch 1/3, Batch 700/1250, Loss: 1.2904
Pooling: none, Epoch 1/3, Batch 750/1250, Loss: 1.2782
Pooling: none, Epoch 1/3, Batch 800/1250, Loss: 1.2773
Pooling: none, Epoch 1/3, Batch 850/1250, Loss: 1.2691
Pooling: none, Epoch 1/3, Batch 900/1250, Loss: 1.2617
Pooling: none, Epoch 1/3, Batch 950/1250, Loss: 1.2600
Pooling: none, Epoch 1/3, Batch 1000/1250, Loss: 1.2486
Pooling: none, Epoch 1/3, Batch 1050/1250, Loss: 1.2432
Pooling: none, Epoch 1/3, Batch 1100/1250, Loss: 1.2365
Pooling: none, Epoch 1/3, Batch 1150/1250, Loss: 1.2272
Pooling: none, Epoch 1/3, Batch 1200/1250, Loss: 1.2169
Pooling: none, Epoch 1/3, Batch 1250/1250, Loss: 1.2064
Pooling: none, Epoch 2/3, Batch 50/1250, Loss: 0.4763
Pooling: none, Epoch 2/3, Batch 100/1250, Loss: 0.5035
Pooling: none, Epoch 2/3, Batch 150/1250, Loss: 0.4873
Pooling: none, Epoch 2/3, Batch 200/1250, Loss: 0.4689
Pooling: none, Epoch 2/3, Batch 250/1250, Loss: 0.4727
Pooling: none, Epoch 2/3, Batch 300/1250, Loss: 0.4743
Pooling: none, Epoch 2/3, Batch 350/1250, Loss: 0.4818
Pooling: none, Epoch 2/3, Batch 400/1250, Loss: 0.4783
Pooling: none, Epoch 2/3, Batch 450/1250, Loss: 0.4830
Pooling: none, Epoch 2/3, Batch 500/1250, Loss: 0.4911
Pooling: none, Epoch 2/3, Batch 550/1250, Loss: 0.4902
Pooling: none, Epoch 2/3, Batch 600/1250, Loss: 0.4984
Pooling: none, Epoch 2/3, Batch 650/1250, Loss: 0.5019
Pooling: none, Epoch 2/3, Batch 700/1250, Loss: 0.5037
Pooling: none, Epoch 2/3, Batch 750/1250, Loss: 0.5046
Pooling: none, Epoch 2/3, Batch 800/1250, Loss: 0.5123
Pooling: none, Epoch 2/3, Batch 850/1250, Loss: 0.5161
Pooling: none, Epoch 2/3, Batch 900/1250, Loss: 0.5234
Pooling: none, Epoch 2/3, Batch 950/1250, Loss: 0.5255
Pooling: none, Epoch 2/3, Batch 1000/1250, Loss: 0.5300
Pooling: none, Epoch 2/3, Batch 1050/1250, Loss: 0.5329
Pooling: none, Epoch 2/3, Batch 1100/1250, Loss: 0.5379
Pooling: none, Epoch 2/3, Batch 1150/1250, Loss: 0.5429
Pooling: none, Epoch 2/3, Batch 1200/1250, Loss: 0.5502
Pooling: none, Epoch 2/3, Batch 1250/1250, Loss: 0.5521
Pooling: none, Epoch 3/3, Batch 50/1250, Loss: 0.2846
Pooling: none, Epoch 3/3, Batch 100/1250, Loss: 0.2825
Pooling: none, Epoch 3/3, Batch 150/1250, Loss: 0.2784
Pooling: none, Epoch 3/3, Batch 200/1250, Loss: 0.2681
Pooling: none, Epoch 3/3, Batch 250/1250, Loss: 0.2818
Pooling: none, Epoch 3/3, Batch 300/1250, Loss: 0.2831
Pooling: none, Epoch 3/3, Batch 350/1250, Loss: 0.2827
Pooling: none, Epoch 3/3, Batch 400/1250, Loss: 0.2895
Pooling: none, Epoch 3/3, Batch 450/1250, Loss: 0.2938
Pooling: none, Epoch 3/3, Batch 500/1250, Loss: 0.2982
Pooling: none, Epoch 3/3, Batch 550/1250, Loss: 0.3053
Pooling: none, Epoch 3/3, Batch 600/1250, Loss: 0.3068
Pooling: none, Epoch 3/3, Batch 650/1250, Loss: 0.3094
Pooling: none, Epoch 3/3, Batch 700/1250, Loss: 0.3128
Pooling: none, Epoch 3/3, Batch 750/1250, Loss: 0.3151
Pooling: none, Epoch 3/3, Batch 800/1250, Loss: 0.3239
Pooling: none, Epoch 3/3, Batch 850/1250, Loss: 0.3334
Pooling: none, Epoch 3/3, Batch 900/1250, Loss: 0.3381
Pooling: none, Epoch 3/3, Batch 950/1250, Loss: 0.3468
Pooling: none, Epoch 3/3, Batch 1000/1250, Loss: 0.3561
Pooling: none, Epoch 3/3, Batch 1050/1250, Loss: 0.3634
Pooling: none, Epoch 3/3, Batch 1100/1250, Loss: 0.3693
Pooling: none, Epoch 3/3, Batch 1150/1250, Loss: 0.3781
Pooling: none, Epoch 3/3, Batch 1200/1250, Loss: 0.3842
Pooling: none, Epoch 3/3, Batch 1250/1250, Loss: 0.3950
Model: word_cnn, Pooling: none, Kernel Sizes: [3, 4, 5, 6], Accuracy: 0.8082, Precision: 0.8052, Recall: 0.8168, F1: 0.8110, Training Time: 67.26s
Start training pooling: adaptive, Kernel sizes: [3, 4, 5, 6]
Pooling: adaptive, Epoch 1/3, Batch 50/1250, Loss: 0.9999
Pooling: adaptive, Epoch 1/3, Batch 100/1250, Loss: 0.9361
Pooling: adaptive, Epoch 1/3, Batch 150/1250, Loss: 0.8758
Pooling: adaptive, Epoch 1/3, Batch 200/1250, Loss: 0.8552
Pooling: adaptive, Epoch 1/3, Batch 250/1250, Loss: 0.8298
Pooling: adaptive, Epoch 1/3, Batch 300/1250, Loss: 0.8019
Pooling: adaptive, Epoch 1/3, Batch 350/1250, Loss: 0.7853
Pooling: adaptive, Epoch 1/3, Batch 400/1250, Loss: 0.7746
Pooling: adaptive, Epoch 1/3, Batch 450/1250, Loss: 0.7669
Pooling: adaptive, Epoch 1/3, Batch 500/1250, Loss: 0.7574
Pooling: adaptive, Epoch 1/3, Batch 550/1250, Loss: 0.7417
Pooling: adaptive, Epoch 1/3, Batch 600/1250, Loss: 0.7370
Pooling: adaptive, Epoch 1/3, Batch 650/1250, Loss: 0.7255
Pooling: adaptive, Epoch 1/3, Batch 700/1250, Loss: 0.7168
Pooling: adaptive, Epoch 1/3, Batch 750/1250, Loss: 0.7063
Pooling: adaptive, Epoch 1/3, Batch 800/1250, Loss: 0.6962
Pooling: adaptive, Epoch 1/3, Batch 850/1250, Loss: 0.6868
Pooling: adaptive, Epoch 1/3, Batch 900/1250, Loss: 0.6786
Pooling: adaptive, Epoch 1/3, Batch 950/1250, Loss: 0.6710
Pooling: adaptive, Epoch 1/3, Batch 1000/1250, Loss: 0.6703
Pooling: adaptive, Epoch 1/3, Batch 1050/1250, Loss: 0.6639
Pooling: adaptive, Epoch 1/3, Batch 1100/1250, Loss: 0.6571
Pooling: adaptive, Epoch 1/3, Batch 1150/1250, Loss: 0.6502
Pooling: adaptive, Epoch 1/3, Batch 1200/1250, Loss: 0.6458
Pooling: adaptive, Epoch 1/3, Batch 1250/1250, Loss: 0.6401
Pooling: adaptive, Epoch 2/3, Batch 50/1250, Loss: 0.3553
Pooling: adaptive, Epoch 2/3, Batch 100/1250, Loss: 0.3698
Pooling: adaptive, Epoch 2/3, Batch 150/1250, Loss: 0.3799
Pooling: adaptive, Epoch 2/3, Batch 200/1250, Loss: 0.3784
Pooling: adaptive, Epoch 2/3, Batch 250/1250, Loss: 0.3755
Pooling: adaptive, Epoch 2/3, Batch 300/1250, Loss: 0.3833
Pooling: adaptive, Epoch 2/3, Batch 350/1250, Loss: 0.3907
Pooling: adaptive, Epoch 2/3, Batch 400/1250, Loss: 0.4006
Pooling: adaptive, Epoch 2/3, Batch 450/1250, Loss: 0.4144
Pooling: adaptive, Epoch 2/3, Batch 500/1250, Loss: 0.4118
Pooling: adaptive, Epoch 2/3, Batch 550/1250, Loss: 0.4111
Pooling: adaptive, Epoch 2/3, Batch 600/1250, Loss: 0.4045
Pooling: adaptive, Epoch 2/3, Batch 650/1250, Loss: 0.4030
Pooling: adaptive, Epoch 2/3, Batch 700/1250, Loss: 0.4038
Pooling: adaptive, Epoch 2/3, Batch 750/1250, Loss: 0.4027
Pooling: adaptive, Epoch 2/3, Batch 800/1250, Loss: 0.4014
Pooling: adaptive, Epoch 2/3, Batch 850/1250, Loss: 0.4037
Pooling: adaptive, Epoch 2/3, Batch 900/1250, Loss: 0.4018
Pooling: adaptive, Epoch 2/3, Batch 950/1250, Loss: 0.4022
Pooling: adaptive, Epoch 2/3, Batch 1000/1250, Loss: 0.4032
Pooling: adaptive, Epoch 2/3, Batch 1050/1250, Loss: 0.4040
Pooling: adaptive, Epoch 2/3, Batch 1100/1250, Loss: 0.4042
Pooling: adaptive, Epoch 2/3, Batch 1150/1250, Loss: 0.4031
Pooling: adaptive, Epoch 2/3, Batch 1200/1250, Loss: 0.4043
Pooling: adaptive, Epoch 2/3, Batch 1250/1250, Loss: 0.4042
Pooling: adaptive, Epoch 3/3, Batch 50/1250, Loss: 0.2368
Pooling: adaptive, Epoch 3/3, Batch 100/1250, Loss: 0.2272
Pooling: adaptive, Epoch 3/3, Batch 150/1250, Loss: 0.2286
Pooling: adaptive, Epoch 3/3, Batch 200/1250, Loss: 0.2344
Pooling: adaptive, Epoch 3/3, Batch 250/1250, Loss: 0.2358
Pooling: adaptive, Epoch 3/3, Batch 300/1250, Loss: 0.2330
Pooling: adaptive, Epoch 3/3, Batch 350/1250, Loss: 0.2363
Pooling: adaptive, Epoch 3/3, Batch 400/1250, Loss: 0.2384
Pooling: adaptive, Epoch 3/3, Batch 450/1250, Loss: 0.2366
Pooling: adaptive, Epoch 3/3, Batch 500/1250, Loss: 0.2373
Pooling: adaptive, Epoch 3/3, Batch 550/1250, Loss: 0.2415
Pooling: adaptive, Epoch 3/3, Batch 600/1250, Loss: 0.2406
Pooling: adaptive, Epoch 3/3, Batch 650/1250, Loss: 0.2422
Pooling: adaptive, Epoch 3/3, Batch 700/1250, Loss: 0.2450
Pooling: adaptive, Epoch 3/3, Batch 750/1250, Loss: 0.2463
Pooling: adaptive, Epoch 3/3, Batch 800/1250, Loss: 0.2482
Pooling: adaptive, Epoch 3/3, Batch 850/1250, Loss: 0.2494
Pooling: adaptive, Epoch 3/3, Batch 900/1250, Loss: 0.2506
Pooling: adaptive, Epoch 3/3, Batch 950/1250, Loss: 0.2520
Pooling: adaptive, Epoch 3/3, Batch 1000/1250, Loss: 0.2527
Pooling: adaptive, Epoch 3/3, Batch 1050/1250, Loss: 0.2539
Pooling: adaptive, Epoch 3/3, Batch 1100/1250, Loss: 0.2578
Pooling: adaptive, Epoch 3/3, Batch 1150/1250, Loss: 0.2617
Pooling: adaptive, Epoch 3/3, Batch 1200/1250, Loss: 0.2634
Pooling: adaptive, Epoch 3/3, Batch 1250/1250, Loss: 0.2650
Model: word_cnn, Pooling: adaptive, Kernel Sizes: [3, 4, 5, 6], Accuracy: 0.8661, Precision: 0.8600, Recall: 0.8769, F1: 0.8684, Training Time: 65.76s

### Hierarchical Word CNN

Bagian ini memakai beberapa Conv1D word-level yang disusun bertingkat.

### Train and Evaluate Hierarchical Word CNN

Fungsi ini mengevaluasi `HierarchicalTextCNN` dengan metrik yang sama seperti eksperimen pooling utama.

In [10]:
def train_and_evaluate_hierarchical(kernel_sizes=[3, 5, 7]):
    model = HierarchicalTextCNN(
        vocab_size=vocab_size,
        embed_dim=300,
        num_filters=100,
        kernel_sizes=kernel_sizes,
        num_classes=2,
    ).to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    print(f"Start training Hierarchical CNN with max pooling and kernel sizes {kernel_sizes}", flush=True)

    if device == "cuda":
        torch.cuda.synchronize()

    start_time = perf_counter()

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0

        for batch_idx, (batch_x, batch_y) in enumerate(train_dataloader, start=1):
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

            if batch_idx % 50 == 0 or batch_idx == len(train_dataloader):
                print(
                    f"Hierarchical CNN, Epoch {epoch + 1}/{num_epochs}, "
                    f"Batch {batch_idx}/{len(train_dataloader)}, "
                    f"Loss: {total_loss / batch_idx:.4f}",
                    flush=True,
                )

    if device == "cuda":
        torch.cuda.synchronize()

    training_time = perf_counter() - start_time

    model.eval()
    y_true = []
    y_pred = []

    with torch.no_grad():
        for batch_x, batch_y in val_dataloader:
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            outputs = model(batch_x)
            probabilities = torch.softmax(outputs, dim=1)
            predictions = probabilities.argmax(dim=1)

            y_true += batch_y.cpu().tolist()
            y_pred += predictions.cpu().tolist()

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    return {
        "model_type": "hierarchical_word_cnn",
        "pooling_type": "max",
        "kernel_sizes": kernel_sizes,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1_score": f1,
        "training_time": training_time,
    }

### Run Hierarchical Word CNN

In [11]:
if "results" not in globals():
    results = []

hierarchical_record = train_and_evaluate_hierarchical()
results = [
    record
    for record in results
    if record.get("model_type") != "hierarchical_word_cnn"
]
results.append(hierarchical_record)

Start training Hierarchical CNN with max pooling and kernel sizes [3, 5, 7]
Hierarchical CNN, Epoch 1/3, Batch 50/1250, Loss: 0.6980
Hierarchical CNN, Epoch 1/3, Batch 100/1250, Loss: 0.6932
Hierarchical CNN, Epoch 1/3, Batch 150/1250, Loss: 0.6912
Hierarchical CNN, Epoch 1/3, Batch 200/1250, Loss: 0.6833
Hierarchical CNN, Epoch 1/3, Batch 250/1250, Loss: 0.6738
Hierarchical CNN, Epoch 1/3, Batch 300/1250, Loss: 0.6609
Hierarchical CNN, Epoch 1/3, Batch 350/1250, Loss: 0.6498
Hierarchical CNN, Epoch 1/3, Batch 400/1250, Loss: 0.6353
Hierarchical CNN, Epoch 1/3, Batch 450/1250, Loss: 0.6192
Hierarchical CNN, Epoch 1/3, Batch 500/1250, Loss: 0.6071
Hierarchical CNN, Epoch 1/3, Batch 550/1250, Loss: 0.5982
Hierarchical CNN, Epoch 1/3, Batch 600/1250, Loss: 0.5884
Hierarchical CNN, Epoch 1/3, Batch 650/1250, Loss: 0.5817
Hierarchical CNN, Epoch 1/3, Batch 700/1250, Loss: 0.5729
Hierarchical CNN, Epoch 1/3, Batch 750/1250, Loss: 0.5648
Hierarchical CNN, Epoch 1/3, Batch 800/1250, Loss: 0.5573
Hierarchical CNN, Epoch 1/3, Batch 850/1250, Loss: 0.5502
Hierarchical CNN, Epoch 1/3, Batch 900/1250, Loss: 0.5445
Hierarchical CNN, Epoch 1/3, Batch 950/1250, Loss: 0.5382
Hierarchical CNN, Epoch 1/3, Batch 1000/1250, Loss: 0.5336
Hierarchical CNN, Epoch 1/3, Batch 1050/1250, Loss: 0.5276
Hierarchical CNN, Epoch 1/3, Batch 1100/1250, Loss: 0.5236
Hierarchical CNN, Epoch 1/3, Batch 1150/1250, Loss: 0.5178
Hierarchical CNN, Epoch 1/3, Batch 1200/1250, Loss: 0.5131
Hierarchical CNN, Epoch 1/3, Batch 1250/1250, Loss: 0.5084
Hierarchical CNN, Epoch 2/3, Batch 50/1250, Loss: 0.3411
Hierarchical CNN, Epoch 2/3, Batch 100/1250, Loss: 0.3443
Hierarchical CNN, Epoch 2/3, Batch 150/1250, Loss: 0.3394
Hierarchical CNN, Epoch 2/3, Batch 200/1250, Loss: 0.3341
Hierarchical CNN, Epoch 2/3, Batch 250/1250, Loss: 0.3283
Hierarchical CNN, Epoch 2/3, Batch 300/1250, Loss: 0.3312
Hierarchical CNN, Epoch 2/3, Batch 350/1250, Loss: 0.3296
Hierarchical CNN, Epoch 2/3, Batch 400/1250, Loss: 0.3321
Hierarchical CNN, Epoch 2/3, Batch 450/1250, Loss: 0.3320
Hierarchical CNN, Epoch 2/3, Batch 500/1250, Loss: 0.3312
Hierarchical CNN, Epoch 2/3, Batch 550/1250, Loss: 0.3309
Hierarchical CNN, Epoch 2/3, Batch 600/1250, Loss: 0.3317
Hierarchical CNN, Epoch 2/3, Batch 650/1250, Loss: 0.3306
Hierarchical CNN, Epoch 2/3, Batch 700/1250, Loss: 0.3300
Hierarchical CNN, Epoch 2/3, Batch 750/1250, Loss: 0.3291
Hierarchical CNN, Epoch 2/3, Batch 800/1250, Loss: 0.3289
Hierarchical CNN, Epoch 2/3, Batch 850/1250, Loss: 0.3296
Hierarchical CNN, Epoch 2/3, Batch 900/1250, Loss: 0.3294
Hierarchical CNN, Epoch 2/3, Batch 950/1250, Loss: 0.3295
Hierarchical CNN, Epoch 2/3, Batch 1000/1250, Loss: 0.3280
Hierarchical CNN, Epoch 2/3, Batch 1050/1250, Loss: 0.3271
Hierarchical CNN, Epoch 2/3, Batch 1100/1250, Loss: 0.3262
Hierarchical CNN, Epoch 2/3, Batch 1150/1250, Loss: 0.3260
Hierarchical CNN, Epoch 2/3, Batch 1200/1250, Loss: 0.3251
Hierarchical CNN, Epoch 2/3, Batch 1250/1250, Loss: 0.3243
Hierarchical CNN, Epoch 3/3, Batch 50/1250, Loss: 0.2016
Hierarchical CNN, Epoch 3/3, Batch 100/1250, Loss: 0.2068
Hierarchical CNN, Epoch 3/3, Batch 150/1250, Loss: 0.2150
Hierarchical CNN, Epoch 3/3, Batch 200/1250, Loss: 0.2180
Hierarchical CNN, Epoch 3/3, Batch 250/1250, Loss: 0.2204
Hierarchical CNN, Epoch 3/3, Batch 300/1250, Loss: 0.2173
Hierarchical CNN, Epoch 3/3, Batch 350/1250, Loss: 0.2182
Hierarchical CNN, Epoch 3/3, Batch 400/1250, Loss: 0.2158
Hierarchical CNN, Epoch 3/3, Batch 450/1250, Loss: 0.2163
Hierarchical CNN, Epoch 3/3, Batch 500/1250, Loss: 0.2184
Hierarchical CNN, Epoch 3/3, Batch 550/1250, Loss: 0.2204
Hierarchical CNN, Epoch 3/3, Batch 600/1250, Loss: 0.2240
Hierarchical CNN, Epoch 3/3, Batch 650/1250, Loss: 0.2236
Hierarchical CNN, Epoch 3/3, Batch 700/1250, Loss: 0.2236
Hierarchical CNN, Epoch 3/3, Batch 750/1250, Loss: 0.2238
Hierarchical CNN, Epoch 3/3, Batch 800/1250, Loss: 0.2257
Hierarchical CNN, Epoch 3/3, Batch 850/1250, Loss: 0.2260
Hierarchical CNN, Epoch 3/3, Batch 900/1250, Loss: 0.2258
Hierarchical CNN, Epoch 3/3, Batch 950/1250, Loss: 0.2259
Hierarchical CNN, Epoch 3/3, Batch 1000/1250, Loss: 0.2269
Hierarchical CNN, Epoch 3/3, Batch 1050/1250, Loss: 0.2271
Hierarchical CNN, Epoch 3/3, Batch 1100/1250, Loss: 0.2278
Hierarchical CNN, Epoch 3/3, Batch 1150/1250, Loss: 0.2290
Hierarchical CNN, Epoch 3/3, Batch 1200/1250, Loss: 0.2292
Hierarchical CNN, Epoch 3/3, Batch 1250/1250, Loss: 0.2303

### Task 1 Top 5 Ranking

In [25]:
task1_results = sorted(
    results if "results" in globals() else [],
    key=lambda record: record["accuracy"],
    reverse=True,
)
task1_top5_results = task1_results[:5]
df_result_1_frame = pd.DataFrame(task1_top5_results)
df_result_1 = df_result_1_frame.drop(columns=['model_key'])

df_result_1

,model_type,pooling_type,kernel_sizes,accuracy,precision,recall,f1_score,training_time
0,word_cnn,avg,"[3, 4, 5, 6]",0.8790,0.864685,0.900735,0.882342,67.186841
1,word_cnn,avg,"[3, 4]",0.8782,0.870130,0.891205,0.880541,40.780969
2,word_cnn,adaptive,"[3, 4, 5, 6]",0.8661,0.860008,0.876911,0.868377,65.764987
3,word_cnn,max,"[3, 4]",0.8658,0.892834,0.833631,0.862218,39.266199
4,word_cnn,max,"[3, 4, 5, 6]",0.8621,0.837454,0.901132,0.868127,65.108639

## Task 2 - Character CNN

- Convert text into character sequences (no word tokenization)
- Build character embeddings
- Apply 1D CNN over character sequences to create word-level representations
- Compare the performance of Character CNN vs Word CNN on the same dataset,
- especially on sentences containing slang, typos, or rare words.

### Character Configuration

`char_max_length` membatasi panjang review dalam satuan karakter agar semua input punya shape yang sama.

In [13]:
char_max_length = 500

### Character Vocabulary

Task 2 tidak memakai word tokenization. Setiap review dibaca sebagai urutan karakter, lalu setiap karakter diberi ID.

In [14]:
char_to_id = {"<pad>": 0, "<unk>": 1}

for review in reviews:
    for char in review.lower():
        if char not in char_to_id:
            char_to_id[char] = len(char_to_id)

char_vocab_size = len(char_to_id)
print("Char vocab size:", char_vocab_size)

Char vocab size: 164

### Character Encoding

Review dipotong sampai `char_max_length`, lalu dipadding dengan ID `<pad>` jika lebih pendek.

In [15]:
def encode_review_chars(text, char_to_id, max_length):
    char_ids = [
        char_to_id.get(char, char_to_id["<unk>"])
        for char in text.lower()[:max_length]
    ]
    char_ids += [char_to_id["<pad>"]] * (max_length - len(char_ids))
    return char_ids


encoded_char_reviews = [
    encode_review_chars(review, char_to_id, char_max_length)
    for review in reviews
]

char_batch_x = torch.tensor(encoded_char_reviews, dtype=torch.long)
char_batch_y = torch.tensor(labels, dtype=torch.long)

print("Char X:", char_batch_x.shape)
print("Char y:", char_batch_y.shape)

Char X: torch.Size([50000, 500])
Char y: torch.Size([50000])

### Character DataLoader

Character CNN memakai split train/validation yang sama dengan Word CNN agar perbandingannya fair.

In [16]:
char_dataset = TensorDataset(char_batch_x, char_batch_y)
char_train_dataset = Subset(char_dataset, train_dataset.indices)
char_val_dataset = Subset(char_dataset, val_dataset.indices)

char_train_dataloader = DataLoader(
    char_train_dataset,
    batch_size=batch_size,
    shuffle=True,
)
char_val_dataloader = DataLoader(
    char_val_dataset,
    batch_size=batch_size,
)

print("Char train data:", len(char_train_dataset))
print("Char validation data:", len(char_val_dataset))

Char train data: 40000
Char validation data: 10000

### Character CNN Training Setup

Bagian ini menyiapkan device dan metrik evaluasi untuk Character CNN.

In [17]:
from time import perf_counter
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

if "trained_models" not in globals():
    trained_models = {}

Using device: cuda

### Train and Evaluate Character CNN

In [18]:
def train_and_evaluate_char(pooling_type="max"):
    model_type = "char_cnn"
    kernel_sizes = [3, 5]

    model = CharCNN(
        char_vocab_size=char_vocab_size,
        char_embed_dim=64,
        num_filters=100,
        kernel_sizes=kernel_sizes,
        num_classes=2,
        pooling_type=pooling_type,
        sequence_length=char_max_length,
    ).to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    print(
        f"Start training {model_type} with {pooling_type} pooling "
        f"and kernel sizes {kernel_sizes}",
        flush=True,
    )

    if device == "cuda":
        torch.cuda.synchronize()

    start_time = perf_counter()

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0

        for batch_idx, (batch_x, batch_y) in enumerate(char_train_dataloader, start=1):
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

            if batch_idx % 50 == 0 or batch_idx == len(char_train_dataloader):
                print(
                    f"Model: {model_type}, Epoch {epoch + 1}/{num_epochs}, "
                    f"Batch {batch_idx}/{len(char_train_dataloader)}, "
                    f"Loss: {total_loss / batch_idx:.4f}",
                    flush=True,
                )

    if device == "cuda":
        torch.cuda.synchronize()

    training_time = perf_counter() - start_time

    model.eval()
    y_true = []
    y_pred = []

    with torch.no_grad():
        for batch_x, batch_y in char_val_dataloader:
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            outputs = model(batch_x)
            probabilities = torch.softmax(outputs, dim=1)
            predictions = probabilities.argmax(dim=1)

            y_true += batch_y.cpu().tolist()
            y_pred += predictions.cpu().tolist()

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)

    model_key = f"char_cnn_{pooling_type}_{'_'.join(map(str, kernel_sizes))}"
    trained_models[model_key] = model

    return {
        "model_type": model_type,
        "pooling_type": pooling_type,
        "kernel_sizes": kernel_sizes,
        "model_key": model_key,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1_score": f1,
        "training_time": training_time,
    }

### Run Character CNN

Jalankan Character CNN biasa dengan beberapa pooling type, seperti eksperimen pooling pada Task 1.

In [19]:
task2_results = []

char_results = []

for pooling_type in ["max", "avg", "none", "adaptive"]:
    record = train_and_evaluate_char(pooling_type=pooling_type)
    char_results.append(record)
    task2_results.append(record)

    print(
        f"Model: {record['model_type']}, "
        f"Pooling: {record['pooling_type']}, "
        f"Kernel Sizes: {record['kernel_sizes']}, "
        f"Accuracy: {record['accuracy']:.4f}, "
        f"Precision: {record['precision']:.4f}, "
        f"Recall: {record['recall']:.4f}, "
        f"F1: {record['f1_score']:.4f}, "
        f"Training Time: {record['training_time']:.2f}s",
        flush=True,
    )

Start training char_cnn with max pooling and kernel sizes [3, 5]
Model: char_cnn, Epoch 1/3, Batch 50/1250, Loss: 0.9019
Model: char_cnn, Epoch 1/3, Batch 100/1250, Loss: 0.8416
Model: char_cnn, Epoch 1/3, Batch 150/1250, Loss: 0.8069
Model: char_cnn, Epoch 1/3, Batch 200/1250, Loss: 0.7826
Model: char_cnn, Epoch 1/3, Batch 250/1250, Loss: 0.7638
Model: char_cnn, Epoch 1/3, Batch 300/1250, Loss: 0.7480
Model: char_cnn, Epoch 1/3, Batch 350/1250, Loss: 0.7364
Model: char_cnn, Epoch 1/3, Batch 400/1250, Loss: 0.7252
Model: char_cnn, Epoch 1/3, Batch 450/1250, Loss: 0.7155
Model: char_cnn, Epoch 1/3, Batch 500/1250, Loss: 0.7077
Model: char_cnn, Epoch 1/3, Batch 550/1250, Loss: 0.7005
Model: char_cnn, Epoch 1/3, Batch 600/1250, Loss: 0.6947
Model: char_cnn, Epoch 1/3, Batch 650/1250, Loss: 0.6895
Model: char_cnn, Epoch 1/3, Batch 700/1250, Loss: 0.6837
Model: char_cnn, Epoch 1/3, Batch 750/1250, Loss: 0.6778
Model: char_cnn, Epoch 1/3, Batch 800/1250, Loss: 0.6738
Model: char_cnn, Epoch 1/3, Batch 850/1250, Loss: 0.6686
Model: char_cnn, Epoch 1/3, Batch 900/1250, Loss: 0.6651
Model: char_cnn, Epoch 1/3, Batch 950/1250, Loss: 0.6610
Model: char_cnn, Epoch 1/3, Batch 1000/1250, Loss: 0.6566
Model: char_cnn, Epoch 1/3, Batch 1050/1250, Loss: 0.6536
Model: char_cnn, Epoch 1/3, Batch 1100/1250, Loss: 0.6495
Model: char_cnn, Epoch 1/3, Batch 1150/1250, Loss: 0.6466
Model: char_cnn, Epoch 1/3, Batch 1200/1250, Loss: 0.6432
Model: char_cnn, Epoch 1/3, Batch 1250/1250, Loss: 0.6400
Model: char_cnn, Epoch 2/3, Batch 50/1250, Loss: 0.5581
Model: char_cnn, Epoch 2/3, Batch 100/1250, Loss: 0.5667
Model: char_cnn, Epoch 2/3, Batch 150/1250, Loss: 0.5620
Model: char_cnn, Epoch 2/3, Batch 200/1250, Loss: 0.5580
Model: char_cnn, Epoch 2/3, Batch 250/1250, Loss: 0.5605
Model: char_cnn, Epoch 2/3, Batch 300/1250, Loss: 0.5558
Model: char_cnn, Epoch 2/3, Batch 350/1250, Loss: 0.5508
Model: char_cnn, Epoch 2/3, Batch 400/1250, Loss: 0.5525
Model: char_cnn, Epoch 2/3, Batch 450/1250, Loss: 0.5507
Model: char_cnn, Epoch 2/3, Batch 500/1250, Loss: 0.5502
Model: char_cnn, Epoch 2/3, Batch 550/1250, Loss: 0.5486
Model: char_cnn, Epoch 2/3, Batch 600/1250, Loss: 0.5485
Model: char_cnn, Epoch 2/3, Batch 650/1250, Loss: 0.5480
Model: char_cnn, Epoch 2/3, Batch 700/1250, Loss: 0.5463
Model: char_cnn, Epoch 2/3, Batch 750/1250, Loss: 0.5470
Model: char_cnn, Epoch 2/3, Batch 800/1250, Loss: 0.5470
Model: char_cnn, Epoch 2/3, Batch 850/1250, Loss: 0.5455
Model: char_cnn, Epoch 2/3, Batch 900/1250, Loss: 0.5446
Model: char_cnn, Epoch 2/3, Batch 950/1250, Loss: 0.5435
Model: char_cnn, Epoch 2/3, Batch 1000/1250, Loss: 0.5416
Model: char_cnn, Epoch 2/3, Batch 1050/1250, Loss: 0.5412
Model: char_cnn, Epoch 2/3, Batch 1100/1250, Loss: 0.5412
Model: char_cnn, Epoch 2/3, Batch 1150/1250, Loss: 0.5415
Model: char_cnn, Epoch 2/3, Batch 1200/1250, Loss: 0.5405
Model: char_cnn, Epoch 2/3, Batch 1250/1250, Loss: 0.5404
Model: char_cnn, Epoch 3/3, Batch 50/1250, Loss: 0.5104
Model: char_cnn, Epoch 3/3, Batch 100/1250, Loss: 0.5134
Model: char_cnn, Epoch 3/3, Batch 150/1250, Loss: 0.5070
Model: char_cnn, Epoch 3/3, Batch 200/1250, Loss: 0.5062
Model: char_cnn, Epoch 3/3, Batch 250/1250, Loss: 0.5158
Model: char_cnn, Epoch 3/3, Batch 300/1250, Loss: 0.5188
Model: char_cnn, Epoch 3/3, Batch 350/1250, Loss: 0.5180
Model: char_cnn, Epoch 3/3, Batch 400/1250, Loss: 0.5191
Model: char_cnn, Epoch 3/3, Batch 450/1250, Loss: 0.5195
Model: char_cnn, Epoch 3/3, Batch 500/1250, Loss: 0.5182
Model: char_cnn, Epoch 3/3, Batch 550/1250, Loss: 0.5187
Model: char_cnn, Epoch 3/3, Batch 600/1250, Loss: 0.5185
Model: char_cnn, Epoch 3/3, Batch 650/1250, Loss: 0.5176
Model: char_cnn, Epoch 3/3, Batch 700/1250, Loss: 0.5176
Model: char_cnn, Epoch 3/3, Batch 750/1250, Loss: 0.5187
Model: char_cnn, Epoch 3/3, Batch 800/1250, Loss: 0.5198
Model: char_cnn, Epoch 3/3, Batch 850/1250, Loss: 0.5193
Model: char_cnn, Epoch 3/3, Batch 900/1250, Loss: 0.5195
Model: char_cnn, Epoch 3/3, Batch 950/1250, Loss: 0.5199
Model: char_cnn, Epoch 3/3, Batch 1000/1250, Loss: 0.5205
Model: char_cnn, Epoch 3/3, Batch 1050/1250, Loss: 0.5213
Model: char_cnn, Epoch 3/3, Batch 1100/1250, Loss: 0.5214
Model: char_cnn, Epoch 3/3, Batch 1150/1250, Loss: 0.5212
Model: char_cnn, Epoch 3/3, Batch 1200/1250, Loss: 0.5209
Model: char_cnn, Epoch 3/3, Batch 1250/1250, Loss: 0.5213
Model: char_cnn, Pooling: max, Kernel Sizes: [3, 5], Accuracy: 0.7722, Precision: 0.7479, Recall: 0.8263, F1: 0.7851, Training Time: 17.11s
Start training char_cnn with avg pooling and kernel sizes [3, 5]
Model: char_cnn, Epoch 1/3, Batch 50/1250, Loss: 0.7062
Model: char_cnn, Epoch 1/3, Batch 100/1250, Loss: 0.6980
Model: char_cnn, Epoch 1/3, Batch 150/1250, Loss: 0.6955
Model: char_cnn, Epoch 1/3, Batch 200/1250, Loss: 0.6920
Model: char_cnn, Epoch 1/3, Batch 250/1250, Loss: 0.6909
Model: char_cnn, Epoch 1/3, Batch 300/1250, Loss: 0.6903
Model: char_cnn, Epoch 1/3, Batch 350/1250, Loss: 0.6891
Model: char_cnn, Epoch 1/3, Batch 400/1250, Loss: 0.6875
Model: char_cnn, Epoch 1/3, Batch 450/1250, Loss: 0.6865
Model: char_cnn, Epoch 1/3, Batch 500/1250, Loss: 0.6857
Model: char_cnn, Epoch 1/3, Batch 550/1250, Loss: 0.6853
Model: char_cnn, Epoch 1/3, Batch 600/1250, Loss: 0.6842
Model: char_cnn, Epoch 1/3, Batch 650/1250, Loss: 0.6842
Model: char_cnn, Epoch 1/3, Batch 700/1250, Loss: 0.6830
Model: char_cnn, Epoch 1/3, Batch 750/1250, Loss: 0.6821
Model: char_cnn, Epoch 1/3, Batch 800/1250, Loss: 0.6804
Model: char_cnn, Epoch 1/3, Batch 850/1250, Loss: 0.6798
Model: char_cnn, Epoch 1/3, Batch 900/1250, Loss: 0.6788
Model: char_cnn, Epoch 1/3, Batch 950/1250, Loss: 0.6780
Model: char_cnn, Epoch 1/3, Batch 1000/1250, Loss: 0.6765
Model: char_cnn, Epoch 1/3, Batch 1050/1250, Loss: 0.6758
Model: char_cnn, Epoch 1/3, Batch 1100/1250, Loss: 0.6751
Model: char_cnn, Epoch 1/3, Batch 1150/1250, Loss: 0.6744
Model: char_cnn, Epoch 1/3, Batch 1200/1250, Loss: 0.6735
Model: char_cnn, Epoch 1/3, Batch 1250/1250, Loss: 0.6726
Model: char_cnn, Epoch 2/3, Batch 50/1250, Loss: 0.6492
Model: char_cnn, Epoch 2/3, Batch 100/1250, Loss: 0.6527
Model: char_cnn, Epoch 2/3, Batch 150/1250, Loss: 0.6501
Model: char_cnn, Epoch 2/3, Batch 200/1250, Loss: 0.6458
Model: char_cnn, Epoch 2/3, Batch 250/1250, Loss: 0.6427
Model: char_cnn, Epoch 2/3, Batch 300/1250, Loss: 0.6421
Model: char_cnn, Epoch 2/3, Batch 350/1250, Loss: 0.6421
Model: char_cnn, Epoch 2/3, Batch 400/1250, Loss: 0.6433
Model: char_cnn, Epoch 2/3, Batch 450/1250, Loss: 0.6424
Model: char_cnn, Epoch 2/3, Batch 500/1250, Loss: 0.6404
Model: char_cnn, Epoch 2/3, Batch 550/1250, Loss: 0.6410
Model: char_cnn, Epoch 2/3, Batch 600/1250, Loss: 0.6409
Model: char_cnn, Epoch 2/3, Batch 650/1250, Loss: 0.6413
Model: char_cnn, Epoch 2/3, Batch 700/1250, Loss: 0.6414
Model: char_cnn, Epoch 2/3, Batch 750/1250, Loss: 0.6404
Model: char_cnn, Epoch 2/3, Batch 800/1250, Loss: 0.6400
Model: char_cnn, Epoch 2/3, Batch 850/1250, Loss: 0.6393
Model: char_cnn, Epoch 2/3, Batch 900/1250, Loss: 0.6383
Model: char_cnn, Epoch 2/3, Batch 950/1250, Loss: 0.6380
Model: char_cnn, Epoch 2/3, Batch 1000/1250, Loss: 0.6370
Model: char_cnn, Epoch 2/3, Batch 1050/1250, Loss: 0.6365
Model: char_cnn, Epoch 2/3, Batch 1100/1250, Loss: 0.6362
Model: char_cnn, Epoch 2/3, Batch 1150/1250, Loss: 0.6357
Model: char_cnn, Epoch 2/3, Batch 1200/1250, Loss: 0.6354
Model: char_cnn, Epoch 2/3, Batch 1250/1250, Loss: 0.6342
Model: char_cnn, Epoch 3/3, Batch 50/1250, Loss: 0.6123
Model: char_cnn, Epoch 3/3, Batch 100/1250, Loss: 0.6098
Model: char_cnn, Epoch 3/3, Batch 150/1250, Loss: 0.6095
Model: char_cnn, Epoch 3/3, Batch 200/1250, Loss: 0.6094
Model: char_cnn, Epoch 3/3, Batch 250/1250, Loss: 0.6113
Model: char_cnn, Epoch 3/3, Batch 300/1250, Loss: 0.6120
Model: char_cnn, Epoch 3/3, Batch 350/1250, Loss: 0.6132
Model: char_cnn, Epoch 3/3, Batch 400/1250, Loss: 0.6128
Model: char_cnn, Epoch 3/3, Batch 450/1250, Loss: 0.6129
Model: char_cnn, Epoch 3/3, Batch 500/1250, Loss: 0.6137
Model: char_cnn, Epoch 3/3, Batch 550/1250, Loss: 0.6140
Model: char_cnn, Epoch 3/3, Batch 600/1250, Loss: 0.6133
Model: char_cnn, Epoch 3/3, Batch 650/1250, Loss: 0.6128
Model: char_cnn, Epoch 3/3, Batch 700/1250, Loss: 0.6133
Model: char_cnn, Epoch 3/3, Batch 750/1250, Loss: 0.6134
Model: char_cnn, Epoch 3/3, Batch 800/1250, Loss: 0.6126
Model: char_cnn, Epoch 3/3, Batch 850/1250, Loss: 0.6131
Model: char_cnn, Epoch 3/3, Batch 900/1250, Loss: 0.6115
Model: char_cnn, Epoch 3/3, Batch 950/1250, Loss: 0.6111
Model: char_cnn, Epoch 3/3, Batch 1000/1250, Loss: 0.6106
Model: char_cnn, Epoch 3/3, Batch 1050/1250, Loss: 0.6093
Model: char_cnn, Epoch 3/3, Batch 1100/1250, Loss: 0.6089
Model: char_cnn, Epoch 3/3, Batch 1150/1250, Loss: 0.6086
Model: char_cnn, Epoch 3/3, Batch 1200/1250, Loss: 0.6082
Model: char_cnn, Epoch 3/3, Batch 1250/1250, Loss: 0.6078
Model: char_cnn, Pooling: avg, Kernel Sizes: [3, 5], Accuracy: 0.7185, Precision: 0.7045, Recall: 0.7600, F1: 0.7312, Training Time: 19.21s
Start training char_cnn with none pooling and kernel sizes [3, 5]
Model: char_cnn, Epoch 1/3, Batch 50/1250, Loss: 1.6700
Model: char_cnn, Epoch 1/3, Batch 100/1250, Loss: 1.1858
Model: char_cnn, Epoch 1/3, Batch 150/1250, Loss: 1.0241
Model: char_cnn, Epoch 1/3, Batch 200/1250, Loss: 0.9442
Model: char_cnn, Epoch 1/3, Batch 250/1250, Loss: 0.9006
Model: char_cnn, Epoch 1/3, Batch 300/1250, Loss: 0.8675
Model: char_cnn, Epoch 1/3, Batch 350/1250, Loss: 0.8484
Model: char_cnn, Epoch 1/3, Batch 400/1250, Loss: 0.8339
Model: char_cnn, Epoch 1/3, Batch 450/1250, Loss: 0.8216
Model: char_cnn, Epoch 1/3, Batch 500/1250, Loss: 0.8092
Model: char_cnn, Epoch 1/3, Batch 550/1250, Loss: 0.8005
Model: char_cnn, Epoch 1/3, Batch 600/1250, Loss: 0.7929
Model: char_cnn, Epoch 1/3, Batch 650/1250, Loss: 0.7865
Model: char_cnn, Epoch 1/3, Batch 700/1250, Loss: 0.7796
Model: char_cnn, Epoch 1/3, Batch 750/1250, Loss: 0.7745
Model: char_cnn, Epoch 1/3, Batch 800/1250, Loss: 0.7692
Model: char_cnn, Epoch 1/3, Batch 850/1250, Loss: 0.7651
Model: char_cnn, Epoch 1/3, Batch 900/1250, Loss: 0.7605
Model: char_cnn, Epoch 1/3, Batch 950/1250, Loss: 0.7567
Model: char_cnn, Epoch 1/3, Batch 1000/1250, Loss: 0.7532
Model: char_cnn, Epoch 1/3, Batch 1050/1250, Loss: 0.7494
Model: char_cnn, Epoch 1/3, Batch 1100/1250, Loss: 0.7462
Model: char_cnn, Epoch 1/3, Batch 1150/1250, Loss: 0.7430
Model: char_cnn, Epoch 1/3, Batch 1200/1250, Loss: 0.7397
Model: char_cnn, Epoch 1/3, Batch 1250/1250, Loss: 0.7365
Model: char_cnn, Epoch 2/3, Batch 50/1250, Loss: 0.6253
Model: char_cnn, Epoch 2/3, Batch 100/1250, Loss: 0.6173
Model: char_cnn, Epoch 2/3, Batch 150/1250, Loss: 0.6173
Model: char_cnn, Epoch 2/3, Batch 200/1250, Loss: 0.6178
Model: char_cnn, Epoch 2/3, Batch 250/1250, Loss: 0.6158
Model: char_cnn, Epoch 2/3, Batch 300/1250, Loss: 0.6174
Model: char_cnn, Epoch 2/3, Batch 350/1250, Loss: 0.6194
Model: char_cnn, Epoch 2/3, Batch 400/1250, Loss: 0.6232
Model: char_cnn, Epoch 2/3, Batch 450/1250, Loss: 0.6217
Model: char_cnn, Epoch 2/3, Batch 500/1250, Loss: 0.6231
Model: char_cnn, Epoch 2/3, Batch 550/1250, Loss: 0.6226
Model: char_cnn, Epoch 2/3, Batch 600/1250, Loss: 0.6224
Model: char_cnn, Epoch 2/3, Batch 650/1250, Loss: 0.6229
Model: char_cnn, Epoch 2/3, Batch 700/1250, Loss: 0.6221
Model: char_cnn, Epoch 2/3, Batch 750/1250, Loss: 0.6226
Model: char_cnn, Epoch 2/3, Batch 800/1250, Loss: 0.6227
Model: char_cnn, Epoch 2/3, Batch 850/1250, Loss: 0.6219
Model: char_cnn, Epoch 2/3, Batch 900/1250, Loss: 0.6207
Model: char_cnn, Epoch 2/3, Batch 950/1250, Loss: 0.6195
Model: char_cnn, Epoch 2/3, Batch 1000/1250, Loss: 0.6190
Model: char_cnn, Epoch 2/3, Batch 1050/1250, Loss: 0.6188
Model: char_cnn, Epoch 2/3, Batch 1100/1250, Loss: 0.6185
Model: char_cnn, Epoch 2/3, Batch 1150/1250, Loss: 0.6186
Model: char_cnn, Epoch 2/3, Batch 1200/1250, Loss: 0.6183
Model: char_cnn, Epoch 2/3, Batch 1250/1250, Loss: 0.6181
Model: char_cnn, Epoch 3/3, Batch 50/1250, Loss: 0.5322
Model: char_cnn, Epoch 3/3, Batch 100/1250, Loss: 0.5339
Model: char_cnn, Epoch 3/3, Batch 150/1250, Loss: 0.5335
Model: char_cnn, Epoch 3/3, Batch 200/1250, Loss: 0.5344
Model: char_cnn, Epoch 3/3, Batch 250/1250, Loss: 0.5392
Model: char_cnn, Epoch 3/3, Batch 300/1250, Loss: 0.5412
Model: char_cnn, Epoch 3/3, Batch 350/1250, Loss: 0.5429
Model: char_cnn, Epoch 3/3, Batch 400/1250, Loss: 0.5451
Model: char_cnn, Epoch 3/3, Batch 450/1250, Loss: 0.5479
Model: char_cnn, Epoch 3/3, Batch 500/1250, Loss: 0.5491
Model: char_cnn, Epoch 3/3, Batch 550/1250, Loss: 0.5486
Model: char_cnn, Epoch 3/3, Batch 600/1250, Loss: 0.5511
Model: char_cnn, Epoch 3/3, Batch 650/1250, Loss: 0.5535
Model: char_cnn, Epoch 3/3, Batch 700/1250, Loss: 0.5544
Model: char_cnn, Epoch 3/3, Batch 750/1250, Loss: 0.5545
Model: char_cnn, Epoch 3/3, Batch 800/1250, Loss: 0.5557
Model: char_cnn, Epoch 3/3, Batch 850/1250, Loss: 0.5573
Model: char_cnn, Epoch 3/3, Batch 900/1250, Loss: 0.5582
Model: char_cnn, Epoch 3/3, Batch 950/1250, Loss: 0.5591
Model: char_cnn, Epoch 3/3, Batch 1000/1250, Loss: 0.5596
Model: char_cnn, Epoch 3/3, Batch 1050/1250, Loss: 0.5599
Model: char_cnn, Epoch 3/3, Batch 1100/1250, Loss: 0.5600
Model: char_cnn, Epoch 3/3, Batch 1150/1250, Loss: 0.5608
Model: char_cnn, Epoch 3/3, Batch 1200/1250, Loss: 0.5617
Model: char_cnn, Epoch 3/3, Batch 1250/1250, Loss: 0.5621
Model: char_cnn, Pooling: none, Kernel Sizes: [3, 5], Accuracy: 0.7082, Precision: 0.6953, Recall: 0.7489, F1: 0.7211, Training Time: 17.54s
Start training char_cnn with adaptive pooling and kernel sizes [3, 5]
Model: char_cnn, Epoch 1/3, Batch 50/1250, Loss: 0.8487
Model: char_cnn, Epoch 1/3, Batch 100/1250, Loss: 0.8184
Model: char_cnn, Epoch 1/3, Batch 150/1250, Loss: 0.7934
Model: char_cnn, Epoch 1/3, Batch 200/1250, Loss: 0.7837
Model: char_cnn, Epoch 1/3, Batch 250/1250, Loss: 0.7679
Model: char_cnn, Epoch 1/3, Batch 300/1250, Loss: 0.7548
Model: char_cnn, Epoch 1/3, Batch 350/1250, Loss: 0.7436
Model: char_cnn, Epoch 1/3, Batch 400/1250, Loss: 0.7350
Model: char_cnn, Epoch 1/3, Batch 450/1250, Loss: 0.7257
Model: char_cnn, Epoch 1/3, Batch 500/1250, Loss: 0.7198
Model: char_cnn, Epoch 1/3, Batch 550/1250, Loss: 0.7124
Model: char_cnn, Epoch 1/3, Batch 600/1250, Loss: 0.7072
Model: char_cnn, Epoch 1/3, Batch 650/1250, Loss: 0.7001
Model: char_cnn, Epoch 1/3, Batch 700/1250, Loss: 0.6945
Model: char_cnn, Epoch 1/3, Batch 750/1250, Loss: 0.6889
Model: char_cnn, Epoch 1/3, Batch 800/1250, Loss: 0.6840
Model: char_cnn, Epoch 1/3, Batch 850/1250, Loss: 0.6784
Model: char_cnn, Epoch 1/3, Batch 900/1250, Loss: 0.6745
Model: char_cnn, Epoch 1/3, Batch 950/1250, Loss: 0.6700
Model: char_cnn, Epoch 1/3, Batch 1000/1250, Loss: 0.6651
Model: char_cnn, Epoch 1/3, Batch 1050/1250, Loss: 0.6599
Model: char_cnn, Epoch 1/3, Batch 1100/1250, Loss: 0.6559
Model: char_cnn, Epoch 1/3, Batch 1150/1250, Loss: 0.6528
Model: char_cnn, Epoch 1/3, Batch 1200/1250, Loss: 0.6495
Model: char_cnn, Epoch 1/3, Batch 1250/1250, Loss: 0.6467
Model: char_cnn, Epoch 2/3, Batch 50/1250, Loss: 0.5358
Model: char_cnn, Epoch 2/3, Batch 100/1250, Loss: 0.5307
Model: char_cnn, Epoch 2/3, Batch 150/1250, Loss: 0.5371
Model: char_cnn, Epoch 2/3, Batch 200/1250, Loss: 0.5470
Model: char_cnn, Epoch 2/3, Batch 250/1250, Loss: 0.5474
Model: char_cnn, Epoch 2/3, Batch 300/1250, Loss: 0.5491
Model: char_cnn, Epoch 2/3, Batch 350/1250, Loss: 0.5497
Model: char_cnn, Epoch 2/3, Batch 400/1250, Loss: 0.5472
Model: char_cnn, Epoch 2/3, Batch 450/1250, Loss: 0.5449
Model: char_cnn, Epoch 2/3, Batch 500/1250, Loss: 0.5430
Model: char_cnn, Epoch 2/3, Batch 550/1250, Loss: 0.5401
Model: char_cnn, Epoch 2/3, Batch 600/1250, Loss: 0.5382
Model: char_cnn, Epoch 2/3, Batch 650/1250, Loss: 0.5391
Model: char_cnn, Epoch 2/3, Batch 700/1250, Loss: 0.5382
Model: char_cnn, Epoch 2/3, Batch 750/1250, Loss: 0.5372
Model: char_cnn, Epoch 2/3, Batch 800/1250, Loss: 0.5350
Model: char_cnn, Epoch 2/3, Batch 850/1250, Loss: 0.5337
Model: char_cnn, Epoch 2/3, Batch 900/1250, Loss: 0.5330
Model: char_cnn, Epoch 2/3, Batch 950/1250, Loss: 0.5320
Model: char_cnn, Epoch 2/3, Batch 1000/1250, Loss: 0.5307
Model: char_cnn, Epoch 2/3, Batch 1050/1250, Loss: 0.5307
Model: char_cnn, Epoch 2/3, Batch 1100/1250, Loss: 0.5303
Model: char_cnn, Epoch 2/3, Batch 1150/1250, Loss: 0.5303
Model: char_cnn, Epoch 2/3, Batch 1200/1250, Loss: 0.5301
Model: char_cnn, Epoch 2/3, Batch 1250/1250, Loss: 0.5285
Model: char_cnn, Epoch 3/3, Batch 50/1250, Loss: 0.4811
Model: char_cnn, Epoch 3/3, Batch 100/1250, Loss: 0.4939
Model: char_cnn, Epoch 3/3, Batch 150/1250, Loss: 0.4920
Model: char_cnn, Epoch 3/3, Batch 200/1250, Loss: 0.4931
Model: char_cnn, Epoch 3/3, Batch 250/1250, Loss: 0.4943
Model: char_cnn, Epoch 3/3, Batch 300/1250, Loss: 0.5009
Model: char_cnn, Epoch 3/3, Batch 350/1250, Loss: 0.5028
Model: char_cnn, Epoch 3/3, Batch 400/1250, Loss: 0.5047
Model: char_cnn, Epoch 3/3, Batch 450/1250, Loss: 0.5062
Model: char_cnn, Epoch 3/3, Batch 500/1250, Loss: 0.5018
Model: char_cnn, Epoch 3/3, Batch 550/1250, Loss: 0.5006
Model: char_cnn, Epoch 3/3, Batch 600/1250, Loss: 0.5020
Model: char_cnn, Epoch 3/3, Batch 650/1250, Loss: 0.5013
Model: char_cnn, Epoch 3/3, Batch 700/1250, Loss: 0.5017
Model: char_cnn, Epoch 3/3, Batch 750/1250, Loss: 0.5035
Model: char_cnn, Epoch 3/3, Batch 800/1250, Loss: 0.5040
Model: char_cnn, Epoch 3/3, Batch 850/1250, Loss: 0.5032
Model: char_cnn, Epoch 3/3, Batch 900/1250, Loss: 0.5029
Model: char_cnn, Epoch 3/3, Batch 950/1250, Loss: 0.5033
Model: char_cnn, Epoch 3/3, Batch 1000/1250, Loss: 0.5037
Model: char_cnn, Epoch 3/3, Batch 1050/1250, Loss: 0.5040
Model: char_cnn, Epoch 3/3, Batch 1100/1250, Loss: 0.5035
Model: char_cnn, Epoch 3/3, Batch 1150/1250, Loss: 0.5041
Model: char_cnn, Epoch 3/3, Batch 1200/1250, Loss: 0.5043
Model: char_cnn, Epoch 3/3, Batch 1250/1250, Loss: 0.5042
Model: char_cnn, Pooling: adaptive, Kernel Sizes: [3, 5], Accuracy: 0.7418, Precision: 0.8707, Recall: 0.5724, F1: 0.6907, Training Time: 16.20s

### Hierarchical Character CNN

Bagian ini memakai `HierarchicalCharCNN`, yaitu beberapa Conv1D karakter yang disusun bertingkat. Jalankan cell ini jika ingin mengambil bonus/eksperimen hierarchical untuk Task 2.

In [20]:
def train_and_evaluate_hierarchical_char(kernel_sizes=[3, 5, 7]):
    model = HierarchicalCharCNN(
        char_vocab_size=char_vocab_size,
        char_embed_dim=64,
        num_filters=100,
        kernel_sizes=kernel_sizes,
        num_classes=2,
    ).to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    print(
        f"Start training hierarchical_char_cnn with max pooling "
        f"and kernel sizes {kernel_sizes}",
        flush=True,
    )

    if device == "cuda":
        torch.cuda.synchronize()

    start_time = perf_counter()

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0

        for batch_idx, (batch_x, batch_y) in enumerate(char_train_dataloader, start=1):
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

            if batch_idx % 50 == 0 or batch_idx == len(char_train_dataloader):
                print(
                    f"Model: hierarchical_char_cnn, Epoch {epoch + 1}/{num_epochs}, "
                    f"Batch {batch_idx}/{len(char_train_dataloader)}, "
                    f"Loss: {total_loss / batch_idx:.4f}",
                    flush=True,
                )

    if device == "cuda":
        torch.cuda.synchronize()

    training_time = perf_counter() - start_time

    model.eval()
    y_true = []
    y_pred = []

    with torch.no_grad():
        for batch_x, batch_y in char_val_dataloader:
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            outputs = model(batch_x)
            probabilities = torch.softmax(outputs, dim=1)
            predictions = probabilities.argmax(dim=1)

            y_true += batch_y.cpu().tolist()
            y_pred += predictions.cpu().tolist()

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)

    return {
        "model_type": "hierarchical_char_cnn",
        "pooling_type": "max",
        "kernel_sizes": kernel_sizes,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1_score": f1,
        "training_time": training_time,
    }


hierarchical_char_record = train_and_evaluate_hierarchical_char()

if "task2_results" not in globals():
    task2_results = []

task2_results = [
    record
    for record in task2_results
    if record.get("model_type") != "hierarchical_char_cnn"
]
task2_results.append(hierarchical_char_record)

Start training hierarchical_char_cnn with max pooling and kernel sizes [3, 5, 7]
Model: hierarchical_char_cnn, Epoch 1/3, Batch 50/1250, Loss: 0.6983
Model: hierarchical_char_cnn, Epoch 1/3, Batch 100/1250, Loss: 0.6919
Model: hierarchical_char_cnn, Epoch 1/3, Batch 150/1250, Loss: 0.6808
Model: hierarchical_char_cnn, Epoch 1/3, Batch 200/1250, Loss: 0.6699
Model: hierarchical_char_cnn, Epoch 1/3, Batch 250/1250, Loss: 0.6636
Model: hierarchical_char_cnn, Epoch 1/3, Batch 300/1250, Loss: 0.6545
Model: hierarchical_char_cnn, Epoch 1/3, Batch 350/1250, Loss: 0.6509
Model: hierarchical_char_cnn, Epoch 1/3, Batch 400/1250, Loss: 0.6431
Model: hierarchical_char_cnn, Epoch 1/3, Batch 450/1250, Loss: 0.6380
Model: hierarchical_char_cnn, Epoch 1/3, Batch 500/1250, Loss: 0.6317
Model: hierarchical_char_cnn, Epoch 1/3, Batch 550/1250, Loss: 0.6280
Model: hierarchical_char_cnn, Epoch 1/3, Batch 600/1250, Loss: 0.6249
Model: hierarchical_char_cnn, Epoch 1/3, Batch 650/1250, Loss: 0.6199
Model: hierarchical_char_cnn, Epoch 1/3, Batch 700/1250, Loss: 0.6172
Model: hierarchical_char_cnn, Epoch 1/3, Batch 750/1250, Loss: 0.6155
Model: hierarchical_char_cnn, Epoch 1/3, Batch 800/1250, Loss: 0.6136
Model: hierarchical_char_cnn, Epoch 1/3, Batch 850/1250, Loss: 0.6106
Model: hierarchical_char_cnn, Epoch 1/3, Batch 900/1250, Loss: 0.6080
Model: hierarchical_char_cnn, Epoch 1/3, Batch 950/1250, Loss: 0.6051
Model: hierarchical_char_cnn, Epoch 1/3, Batch 1000/1250, Loss: 0.6033
Model: hierarchical_char_cnn, Epoch 1/3, Batch 1050/1250, Loss: 0.6005
Model: hierarchical_char_cnn, Epoch 1/3, Batch 1100/1250, Loss: 0.5996
Model: hierarchical_char_cnn, Epoch 1/3, Batch 1150/1250, Loss: 0.5972
Model: hierarchical_char_cnn, Epoch 1/3, Batch 1200/1250, Loss: 0.5964
Model: hierarchical_char_cnn, Epoch 1/3, Batch 1250/1250, Loss: 0.5945
Model: hierarchical_char_cnn, Epoch 2/3, Batch 50/1250, Loss: 0.5686
Model: hierarchical_char_cnn, Epoch 2/3, Batch 100/1250, Loss: 0.5626
Model: hierarchical_char_cnn, Epoch 2/3, Batch 150/1250, Loss: 0.5520
Model: hierarchical_char_cnn, Epoch 2/3, Batch 200/1250, Loss: 0.5450
Model: hierarchical_char_cnn, Epoch 2/3, Batch 250/1250, Loss: 0.5463
Model: hierarchical_char_cnn, Epoch 2/3, Batch 300/1250, Loss: 0.5462
Model: hierarchical_char_cnn, Epoch 2/3, Batch 350/1250, Loss: 0.5472
Model: hierarchical_char_cnn, Epoch 2/3, Batch 400/1250, Loss: 0.5424
Model: hierarchical_char_cnn, Epoch 2/3, Batch 450/1250, Loss: 0.5410
Model: hierarchical_char_cnn, Epoch 2/3, Batch 500/1250, Loss: 0.5393
Model: hierarchical_char_cnn, Epoch 2/3, Batch 550/1250, Loss: 0.5388
Model: hierarchical_char_cnn, Epoch 2/3, Batch 600/1250, Loss: 0.5394
Model: hierarchical_char_cnn, Epoch 2/3, Batch 650/1250, Loss: 0.5383
Model: hierarchical_char_cnn, Epoch 2/3, Batch 700/1250, Loss: 0.5373
Model: hierarchical_char_cnn, Epoch 2/3, Batch 750/1250, Loss: 0.5351
Model: hierarchical_char_cnn, Epoch 2/3, Batch 800/1250, Loss: 0.5350
Model: hierarchical_char_cnn, Epoch 2/3, Batch 850/1250, Loss: 0.5351
Model: hierarchical_char_cnn, Epoch 2/3, Batch 900/1250, Loss: 0.5342
Model: hierarchical_char_cnn, Epoch 2/3, Batch 950/1250, Loss: 0.5330
Model: hierarchical_char_cnn, Epoch 2/3, Batch 1000/1250, Loss: 0.5322
Model: hierarchical_char_cnn, Epoch 2/3, Batch 1050/1250, Loss: 0.5304
Model: hierarchical_char_cnn, Epoch 2/3, Batch 1100/1250, Loss: 0.5298
Model: hierarchical_char_cnn, Epoch 2/3, Batch 1150/1250, Loss: 0.5296
Model: hierarchical_char_cnn, Epoch 2/3, Batch 1200/1250, Loss: 0.5275
Model: hierarchical_char_cnn, Epoch 2/3, Batch 1250/1250, Loss: 0.5276
Model: hierarchical_char_cnn, Epoch 3/3, Batch 50/1250, Loss: 0.5069
Model: hierarchical_char_cnn, Epoch 3/3, Batch 100/1250, Loss: 0.4969
Model: hierarchical_char_cnn, Epoch 3/3, Batch 150/1250, Loss: 0.4957
Model: hierarchical_char_cnn, Epoch 3/3, Batch 200/1250, Loss: 0.5015
Model: hierarchical_char_cnn, Epoch 3/3, Batch 250/1250, Loss: 0.4985
Model: hierarchical_char_cnn, Epoch 3/3, Batch 300/1250, Loss: 0.5008
Model: hierarchical_char_cnn, Epoch 3/3, Batch 350/1250, Loss: 0.5013
Model: hierarchical_char_cnn, Epoch 3/3, Batch 400/1250, Loss: 0.4992
Model: hierarchical_char_cnn, Epoch 3/3, Batch 450/1250, Loss: 0.4979
Model: hierarchical_char_cnn, Epoch 3/3, Batch 500/1250, Loss: 0.4990
Model: hierarchical_char_cnn, Epoch 3/3, Batch 550/1250, Loss: 0.5000
Model: hierarchical_char_cnn, Epoch 3/3, Batch 600/1250, Loss: 0.5007
Model: hierarchical_char_cnn, Epoch 3/3, Batch 650/1250, Loss: 0.5008
Model: hierarchical_char_cnn, Epoch 3/3, Batch 700/1250, Loss: 0.5013
Model: hierarchical_char_cnn, Epoch 3/3, Batch 750/1250, Loss: 0.5015
Model: hierarchical_char_cnn, Epoch 3/3, Batch 800/1250, Loss: 0.5000
Model: hierarchical_char_cnn, Epoch 3/3, Batch 850/1250, Loss: 0.5012
Model: hierarchical_char_cnn, Epoch 3/3, Batch 900/1250, Loss: 0.5023
Model: hierarchical_char_cnn, Epoch 3/3, Batch 950/1250, Loss: 0.5018
Model: hierarchical_char_cnn, Epoch 3/3, Batch 1000/1250, Loss: 0.5014
Model: hierarchical_char_cnn, Epoch 3/3, Batch 1050/1250, Loss: 0.5013
Model: hierarchical_char_cnn, Epoch 3/3, Batch 1100/1250, Loss: 0.5006
Model: hierarchical_char_cnn, Epoch 3/3, Batch 1150/1250, Loss: 0.5001
Model: hierarchical_char_cnn, Epoch 3/3, Batch 1200/1250, Loss: 0.4993
Model: hierarchical_char_cnn, Epoch 3/3, Batch 1250/1250, Loss: 0.4985

## Compare Word CNN vs Character CNN

Bagian ini membandingkan model Word CNN dan Character CNN pada contoh kalimat slang, typo, atau rare words. Cell ini dijalankan setelah eksperimen Word CNN dan Character CNN selesai, karena membutuhkan model yang sudah tersimpan di `trained_models`.

In [24]:
word_source = results if "results" in globals() else []
char_source = char_results if "char_results" in globals() else []
model_store = trained_models if "trained_models" in globals() else {}

word_candidates = [
    record
    for record in word_source
    if record.get("model_type") == "word_cnn" and record.get("model_key") in model_store
]
char_candidates = [
    record
    for record in char_source
    if record.get("model_type") == "char_cnn" and record.get("model_key") in model_store
]

if not word_candidates or not char_candidates:
    raise ValueError("Run Word CNN and Character CNN training cells first.")

best_word_record = max(word_candidates, key=lambda record: record["accuracy"])
best_char_record = max(char_candidates, key=lambda record: record["accuracy"])

best_word_model = model_store[best_word_record["model_key"]]
best_char_model = model_store[best_char_record["model_key"]]

slangtypodata = [
    "omg this movie was sickkkk, def 10/10",
    "the ending made me cry fr fr, so emotional",
    "worst cinemax experience ever, rly bad acting",
    "ngl the cgi was kinda sus and cheap",
    "totally mindblown! dat plot twist was cray",
    "idk why ppl hate this, it was p cool",
    "just watched it and wowww, absolute masterpiece",
    "boring af, i almost fell asleep in d theater",
    "the soundtrack was a whole vibe, luvvv it",
    "istg this is the best film of 2026, no cap"
]


def predict_review(model, encoded_review):
    model.eval()
    input_tensor = torch.tensor([encoded_review], dtype=torch.long).to(device)

    with torch.no_grad():
        outputs = model(input_tensor)
        probabilities = torch.softmax(outputs, dim=1).squeeze(0)
        prediction = probabilities.argmax().item()

    return prediction, probabilities[prediction].item()


comparison_rows = []

for review in slangtypodata:
    word_encoded = encode_review(review, word_to_id, max_length)
    char_encoded = encode_review_chars(review, char_to_id, char_max_length)

    word_prediction, word_confidence = predict_review(best_word_model, word_encoded)
    char_prediction, char_confidence = predict_review(best_char_model, char_encoded)

    comparison_rows.append({
        "review": review,
        "word_prediction": "positive" if word_prediction == 1 else "negative",
        "word_confidence": word_confidence,
        "char_prediction": "positive" if char_prediction == 1 else "negative",
        "char_confidence": char_confidence,
        "word_model": best_word_record["model_key"],
        "char_model": best_char_record["model_key"],
    })

print("Word CNN vs Character CNN")
slang_typo_rare_comparison = pd.DataFrame(comparison_rows)
slang_typo_rare_comparison

Word CNN vs Character CNN

,review,word_prediction,word_confidence,char_prediction,char_confidence,word_model,char_model
0,"omg this movie was sickkkk, def 10/10",positive,0.634045,positive,0.557419,word_cnn_avg_3_4_5_6,char_cnn_max_3_5
1,"the ending made me cry fr fr, so emotional",positive,0.661720,positive,0.601238,word_cnn_avg_3_4_5_6,char_cnn_max_3_5
2,"worst cinemax experience ever, rly bad acting",negative,0.976381,negative,0.954350,word_cnn_avg_3_4_5_6,char_cnn_max_3_5
3,ngl the cgi was kinda sus and cheap,negative,0.651753,negative,0.686422,word_cnn_avg_3_4_5_6,char_cnn_max_3_5
4,totally mindblown! dat plot twist was cray,negative,0.521632,negative,0.523562,word_cnn_avg_3_4_5_6,char_cnn_max_3_5
5,"idk why ppl hate this, it was p cool",negative,0.550403,positive,0.559360,word_cnn_avg_3_4_5_6,char_cnn_max_3_5
6,"just watched it and wowww, absolute masterpiece",positive,0.775537,positive,0.603846,word_cnn_avg_3_4_5_6,char_cnn_max_3_5
7,"boring af, i almost fell asleep in d theater",negative,0.909897,negative,0.628657,word_cnn_avg_3_4_5_6,char_cnn_max_3_5
8,"the soundtrack was a whole vibe, luvvv it",positive,0.581065,positive,0.692707,word_cnn_avg_3_4_5_6,char_cnn_max_3_5
9,"istg this is the best film of 2026, no cap",positive,0.733415,negative,0.569433,word_cnn_avg_3_4_5_6,char_cnn_max_3_5

### Task 2 Top 5 Ranking

In [26]:
if "task2_results" not in globals() or not task2_results:
    raise ValueError("Run Task 2 training cells first.")

task2_results = sorted(
    task2_results,
    key=lambda record: record["accuracy"],
    reverse=True,
)
task2_top5_results = task2_results[:5]

df_result_2_frame = pd.DataFrame(task2_top5_results)
df_result_2 = df_result_2_frame.drop(columns=['model_key'])

df_result_2

,model_type,pooling_type,kernel_sizes,accuracy,precision,recall,f1_score,training_time
0,char_cnn,max,"[3, 5]",0.7722,0.747889,0.826285,0.785135,17.106889
1,hierarchical_char_cnn,max,"[3, 5, 7]",0.7599,0.708347,0.889617,0.788700,27.866008
2,char_cnn,adaptive,"[3, 5]",0.7418,0.870734,0.572365,0.690704,16.200598
3,char_cnn,avg,"[3, 5]",0.7185,0.704453,0.759976,0.731162,19.208938
4,char_cnn,none,"[3, 5]",0.7082,0.695300,0.748858,0.721086,17.538617